import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kurumsal Üyelik ve Mağaza Sözleşmesi | TatilDesen",
  description: "Kurumsal üyelik ve mağaza sözleşmesi metni.",
};

const agreementText = `Kurumsal Üyelik ve Mağaza Kullanım Sözleşmesi
 
TATİLDESEN.COM KURUMSAL ÜYELİK VE MAĞAZA KULLANIM SÖZLEŞMESİ
1. Taraflar
İşbu sözleşme (bundan böyle “Sözleşme” olarak anılacaktır), aşağıda bilgileri verilen taraflar arasında, KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN  (bundan böyle “Tatildesen” olarak anılacaktır) ile Tatildesen.com platformunda kurumsal hesap oluşturan ve hizmetlerden yararlanan tüzel kişi veya ticari işletme (bundan böyle “Kurumsal Üye” olarak anılacaktır) arasında elektronik ortamda akdedilmiştir.
2. Tanımlar
Portal: Tatildesen.com’un internet sitesi ve mobil uygulamalar aracılığıyla sunduğu hizmetler.Kurumsal Üye: Ticari faaliyet yürüten, Tatildesen.com'da ilan yayınlayan veya hizmet alan işletmeler, şirketler, şahıs firmaları.Mağaza: Kurumsal Üye'nin Tatildesen.com üzerinde ticari faaliyetlerini yürüttüğü ve ilanlarını yönettiği özel alan.Yetkili Kullanıcı: Kurumsal Üye tarafından yetkilendirilen ve Mağaza yönetimini üstlenen kişi.İlan: Kurumsal Üye'nin satmak veya tanıtmak amacıyla platformda yayınladığı ürün veya hizmet duyurusu.
3. Kurumsal Üyelik ve Mağaza Yönetimi
Kurumsal Üyelik, yalnızca ticari işletmeler, şahıs şirketleri veya tüzel kişiler tarafından oluşturulabilir. Kurumsal Üye, Mağaza oluşturmak ve ilan yayınlamak için gerekli olan tüm bilgi ve belgeleri Tatildesen’e sunmakla yükümlüdür. Yetkili Kullanıcılar, işletme adına ilan yayınlamak, ilanları yönetmek ve ödeme işlemlerini yürütmek için belirlenebilir. Tatildesen, Kurumsal Üye’nin verdiği bilgilerin doğruluğunu araştırma ve gerekirse ek belgeler talep etme hakkına sahiptir.
Yetkili Kullanıcı ve Personel Sorumluluğu (Müteselsil Sorumluluk): Kurumsal Üye (Mağaza Sahibi); sisteme tanımladığı 'Yetkili Kullanıcı', 'Danışman' veya 'Alt Kullanıcı' statüsündeki kişilerin (personel, iş ortağı vb.) Portal üzerindeki tüm işlem, eylem, taahhüt ve ihmallerinden; bizzat kendisi yapmış gibi müştereken ve müteselsilen sorumludur. Kurumsal Üye, "İşlemi bilgim dışında personel yaptı", "Personel işten ayrıldı" veya "Yetkisiz işlemdi" gibi savunmalarla Tatildesen'a veya üçüncü kişilere karşı sorumluluktan kurtulamaz. Mağaza üzerinden yapılan her işlem, doğrudan Kurumsal Üye'yi bağlar.
Devir, Kiralama ve Alt Kullanım Yasağı: Kurumsal Üyelik, Mağaza açma yetkisi ve satın alınan ilan paketleri münhasıran Üye'ye aittir. Üye, mağazasını kısmen veya tamamen üçüncü şahıslara kiralayamaz, şifresini bedelli veya bedelsiz olarak başkalarıyla paylaşamaz, sahip olduğu 'ilan yayınlama haklarını' üçüncü kişilere satamaz veya devredemez. Platform üzerinde 'Gizli Acentelik' veya 'Komisyonlu İlan Girme' faaliyeti yürütülemez. Tespiti halinde Tatildesen, ilgili hesabı derhal ve tazminatsız olarak kapatma, kalan bakiyeyi irat kaydetme ve uğradığı gelir kaybını tazmin etme hakkına sahiptir.
Mağaza Adı ve URL Kısıtlaması: Kurumsal Üye'nin belirleyeceği Mağaza Adı ve alt alan adı (subdomain); üçüncü şahısların tescilli markalarını, siyasi/ideolojik ifadeleri, rakip platform isimlerini, web sitesi adreslerini (.com, .net, .org vb.), e-posta adreslerini veya telefon numaralarını içeremez. Mağaza isminde, müşteriyi doğrudan platform dışına yönlendirmeyi amaçlayan ifadeler (Örn: "Wp-0532...", "Sitemiz-Nokta-Kom") kullanılamaz. Tatildesen, bu kurala uymayan, yanıltıcı veya marka ihlali yaratan mağaza isimlerini Üye'yesormaksızın tek taraflı olarak (re'sen) değiştirme, uygun bir isme dönüştürme veya düzeltilinceye kadar mağazayı askıya alma hakkına sahiptir.
Pasif Hesap Yönetimi ve Veri Temizliği: Veri güvenliğini sağlamak, sistem performansını korumak ve KVKK 'Veri Minimizasyonu' ilkesine uymak amacıyla; aktif bir ücretli abonelik paketi bulunmayan veya son 6 aydır sisteme giriş yapmayan/işlem görmeyen hesaplar (özellikle Alt Kullanıcı/Personel hesapları); Tatildesen tarafından önce 'Pasif' statüsüne alınabilir, ardından sistemden kalıcı olarak silinebilir. Kurumsal Üye, kendi tanımladığı alt kullanıcıların pasife alınması veya silinmesi nedeniyle veri kaybı iddiasında bulunamaz.
Proje Satış ve Markalı Konut Kısıtlaması: Proje Satış ; münhasıran inşaat firmaları (Müteahhitler) ve bu projelerin satış yetkisine sahip pazarlama ofisleri tarafından; yalnızca 'Sıfır' (Birinci El)statüsündeki markalı konut/ticari projelerin tanıtımı için kullanılabilir. Bu mağaza tipinde; projeye ait olmayan bireysel gayrimenkuller, ikinci el (resale) emlak portföyleri veya vasıta/araç ilanları yayınlanamaz. Tatildesen, bu kurala aykırı olarak Proje ilanı içerisine girilen ikinci el veya vasıta ilanlarını uyarı yapmaksızın yayından kaldırma, tekrarı halinde mağaza statüsünü standart 'Emlak Ofisi' tipine düşürme hakkına sahiptir.
Kurumsal Mağaza paneline tanımlanabilecek maksimum 'Alt Kullanıcı' (Personel, Danışman, Satış Temsilcisi vb.) sayısı; Mağaza'nın türü, aktif ilan kapasitesi ve firmanın ticari hacmi dikkate alınarak münhasıran Tatildesen tarafından belirlenir. Tatildesen, paket içeriklerinde ve ücretsiz kullanıcı kotalarında tek taraflı değişiklik yapma hakkını saklı tutar.
4. İlan Verme Kuralları
4.1. Genel İlan Kuralları
İlanlar doğru, eksiksiz ve güncel bilgiler içermelidir. Yanıltıcı, eksik veya hatalı bilgi içeren ilanlar yayından kaldırılabilir. Aynı ürün veya hizmet için birden fazla ilan açmak yasaktır. Aynı içerikte yinelenen ilanlar otomatik olarak kaldırılacaktır. Fiyat bilgisi zorunludur ve sezona veya sezon içinde de fiyatlar değişiklik gösteriyorsa her tarih için takvim üzerinde KDV DAHİL fiyatlarını girmek zorundadır. Eksik veya gerçeğe aykırı fiyat beyanları içeren ilanlar yayınlanmaz. Ürünlerde fahiş şekilde az veya fazla fiyatlandırma durumunda ilan, firmamız tarafından askıya alınabilecektir.
4.2. Yasaklı ve Kısıtlı İlanlar
Yanıltıcı, aldatıcı, sahte veya gerçek dışı bilgiler içeren ilanlar yasaktır.Her türlü müstehcen, pornografik içerik veya yasa dışı unsurlar içeren ilanlar yasaktır.Terör propagandası, kamu düzenini bozan içerikler, devlet aleyhine ifadeler içeren ilanlar yasaktır.Üçüncü şahısların marka, patent veya telif hakkını ihlal eden içerikler yasaktır.Sahte, çalıntı veya yasalara aykırı ürünlerin satışına yönelik ilanlar yayınlanamaz.Yanlış kategoriye yerleştirilmiş ilanlar düzeltme talebiyle reddedilebilir veya kaldırılabilir.
Fikri Mülkiyet İhlali ve Uyar-Kaldır Politikası:
1. Replika/Taklit Ürün Yasağı: Üye, Tatildesen.com üzerinde; üçüncü şahısların fikri ve sınai mülkiyet haklarını (Marka, Patent, Tasarım, Telif) ihlal eden; "Replica", "Çakma", "Birebir", "A Kalite", "İhraç Fazlası" veya "Mirror" gibi ifadelerle pazarlanan taklit/sahte ürünleri satamaz. Bu tür ürünlerin satışı Türk Ticaret Kanunu ve Sınai Mülkiyet Kanunu'na göre suçtur.
2. Uyar-Kaldır Prensibi: Tatildesen, 5651 sayılı Kanun kapsamında "Yer Sağlayıcı" sıfatıyla hareket eder. Telif hakkı veya marka sahibi olduğunu belgeleyen kişi/kurumlardan şikayet gelmesi halinde; Tatildesen, ihlale konu ilanı herhangi bir ön incelemeye veya yargı kararına gerek duymaksızın derhal yayından kaldırma, Üye'nin hesabını askıya alma ve Üye'nin kimlik/iletişim bilgilerini yasal süreç başlatılması için hak sahibine veya savcılığa iletme hakkına sahiptir.
3. Tazminat ve Rücu: Üye'nin marka hakkına tecavüz teşkil eden (sahte) ürün satışı nedeniyle, Tatildesen'in üçüncü kişilere tazminat ödemek zorunda kalması veya idari/adli para cezasına çarptırılması durumunda; ödenen tüm bedeller, avukatlık ücretleri ve dosya masraflarıyla birlikte Üye'ye rücu edilir (yansıtılır).
 
4.3. İlan İçeriği ve Görselleri ile İlgili Kurallar
İlan başlığı ve açıklaması, ilan konusu ile doğrudan ilgili olmalıdır. İlan açıklaması ve görseller, doğrudan satışı yapılan ürün veya hizmetle ilgili olmalıdır. İlan görsellerinde, müstehcen içerikler, yanıltıcı bilgiler, üçüncü kişilere ait hakları ihlal eden içerikler kullanılamaz. Başka bir platformdan alınmış, üzerinde düzenleme yapılmış veya yetkisiz olarak kullanılan görseller içeren ilanlar kaldırılır. Görsellerde web sitesi logosu veya iletişim bilgileri bulunamaz. İlan açıklaması kısmında iletişim bilgileri bulunamaz. İlan başlığı, açıklaması, mağaza tanıtım yazısı veya görselleri içerisinde; Tatildesen.com dışındaki başka bir web sitesine, e-ticaret platformuna, sosyal medya hesabına (Instagram, Facebook vb.) veya kişisel bloglara yönlendirme yapan 'link', URL adresi, karekod (QR Kod) veya yönlendirici kısaltmalar paylaşılamaz. Bu tür trafik kaçırmaya yönelik içerikler tespit edildiğinde, Tatildesen ilanı yayından kaldırma, mağazayı askıya alma ve ihlal tekrarında üyeliği iptal etme hakkına sahiptir.
İlan açıklamasının doğruluğunun ve yasal uygunluğunun kontrol ve düzenleme sorumluluğu tamamen ilan sahibine aittir. Kullanıcı, platform tarafından oluşturulan açıklamaları kontrol etmekle yükümlü olup, gerektiğinde düzeltme yapabileceğini kabul eder. Tatildesen.com, kullanıcı tarafından sağlanan eksik, yanlış veya yanıltıcı bilgi sebebiyle ortaya çıkabilecek herhangi bir doğrudan ya da dolaylı zarardan sorumlu değildir.
Kullanıcı, beyan ettiği tüm bilgilerin gerçeğe uygun olduğunu ve üçüncü kişi haklarını ihlal etmediğini taahhüt eder. Aksi takdirde doğacak her türlü hukuki ve cezai sorumluluk kendisine aittir.
AI ve İşlenmiş Görsel Hakkı: Kurumsal Üye, sisteme yüklediği ham görseller üzerinde Tatildesen tarafından teknik iyileştirmeler (Yapay zeka ile netleştirme, arka plan temizleme, filigran ekleme, boyutlandırma vb.) yapılması halinde; ortaya çıkan bu 'İyileştirilmiş/İşlenmiş İçerikler' üzerinde FSEK kapsamında doğan işleme eser haklarının Tatildesen'a ait olduğunu kabul eder. Üye, Tatildesen'ın sunucu kaynakları ve teknolojisi ile üretilen bu işlenmiş görselleri kopyalayarak rakip platformlarda kullanamaz. Kullanması halinde Tatildesen'in telif tazminatı hakkı saklıdır.
Rücu Hakkı: Üye'nin işbu Sözleşme'ye, İlan Verme Kuralları'na, Fikir ve Sanat Eserleri Kanunu'na veya ilgili mevzuata aykırı davranışları nedeniyle; Tatildesen'in kamu kurumlarına (BTK, Rekabet Kurumu, Ticaret Bakanlığı vb.) idari para cezası ödemek zorunda kalması veya üçüncü kişilere tazminat ödemesi halinde; Tatildesen, ödediği tüm bedelleri, yargılama giderlerini ve avukatlık ücretlerini ferileriyle birlikte Üye'ye rücu etme (yansıtma) hakkına sahiptir. Üye, Tatildesen'ın ilk yazılı talebinde bu tutarları itirazsız olarak nakden ve defaten ödemeyi kabul ve taahhüt eder.
Lisans ve Pazarlama Hakkı: Kurumsal Üye, Portal'a yüklediği her türlü görselin, videonun ve içeriğin; Tatildesen tarafından platformun tanıtımı, reklamı ve pazarlaması amacıyla her türlü mecrada (Sosyal Medya, TV, Dijital Reklamlar, Billboard, Basılı Materyal vb.) süre, yer ve mecra sınırı olmaksızın, bedelsiz olarak kullanılabileceğini, çoğaltılabileceğini ve işlenebileceğini kabul eder. Üye, bu içerikler üzerinde Tatildesen'e gayrikabili rücu (geri dönülemez) ve süresiz bir kullanım lisansı verdiğini, bu kullanım nedeniyle herhangi bir telif ücreti veya hak talep etmeyeceğini taahhüt eder.
İlan Tarihi Manipülasyonu (Sil-Yükle Yasağı): Kurumsal Üye, Doping/Boost hizmeti satın almadan ilan tarihini güncellemek veya ilanı listelerde üst sıralara taşımak amacıyla; yayındaki veya süresi bitmiş bir ilanı silip, aynı özelliklere, görsellere veya açıklamaya sahip ürünü/hizmeti 'yeni bir ilanmış gibi' sisteme tekrar giremez. Tatildesen’in yapay zeka ve içerik eşleştirme algoritmaları bu manipülasyonu (Sil-Yükle) tespit ettiğinde; mükerrer ilanı silme, üyeliği askıya alma ve bu yöntemle elde edilen haksız görünürlük bedelini (geçmişe dönük Doping ücreti olarak) talep etme hakkına sahiptir.
Tatildesen, alıcıların doğru bilgilendirilmesi ve şeffaf bir pazar yapısının korunması amacıyla; ilanın fiyat değişim geçmişini, yapılan indirim oranlarını, ilk fiyat/son fiyat karşılaştırmalarını ve artış grafiklerini 'Fiyat Tarihçesi' özelliği altında diğer kullanıcılara ve ziyaretçilere açıkça gösterme hakkına sahiptir. Kurumsal Üye, sisteme girdiği fiyat verilerinin "Ticari Sır" niteliğinde olmadığını; bu verilerin istatistiki amaçlarla işlenmesine, yayınlanmasına ve geçmişe dönük fiyat hareketlerinin platformda ifşa edilmesine gayrikabili rücu (geri dönülemez) onay verir. Üye, fiyat tarihçesinin gösterilmesi nedeniyle ticari itibar kaybı, satışın zorlaşması veya zarar iddiasında bulunamaz.
Ayrımcılık Yasağı ve Ortak Yaşam Kısıtlaması (TİHEK):
1. Ayrımcılık Yasağı: Kurumsal Üye, ilan başlığında veya açıklamasında; 6701 sayılı Türkiye İnsan Hakları ve Eşitlik Kurumu (TİHEK) Kanunu'na aykırı olarak; ırk, renk, cinsiyet, dil, din, inanç, mezhep, servet, doğum, medeni hal (bekar/evli/boşanmış), engellilik veya yaş temellerine dayalı ayrımcılık içeren ifadeler kullanamaz (Örn: "Bekara/Öğrenciye verilmez", "Sadece aileye", "Yabancıya olmaz"). Bu tür ifadeler içeren ilanlar reddedilir. Ayrımcılık yasağının ihlali nedeniyle TİHEK tarafından Tatildesen'a kesilecek idari para cezaları Üye'ye rücu edilir.
2. Ortak Yaşam İlanı Yasağı: Platform üzerinde güvenlik gerekçesiyle "Ev Arkadaşı", "Oda Arkadaşı", "Kalacak Yer Karşılığı..." veya "Paylaşımlı Ev" arayışına yönelik ilanlar girilmesi yasaktır. Tatildesen, bu tür ilanları ahlaka ve genel güvenliğe aykırı kabul ederek derhal yayından kaldırır.
Canlı Hayvan Ticareti Yasağı: Kurumsal Üye (Pet Shop vb.), Platform üzerinden yalnızca evcil hayvan malzemesi (mama, aksesuar, kafes vb.) satışı yapabilir. Platform üzerinden canlı hayvan satışı yapılması yasaktır. Kurumsal mağaza vitrininde kedi, köpek vb. canlı hayvanların fiyat etiketiyle sergilenmesi mevzuata aykırı olduğundan, bu tür ilanlar reddedilir.
Tatildesen.com'da hayvan satışı yasaktır. Sadece ücretsiz sahiplendirme ilanı verebilirsiniz. İlan verirken Fiyat alanını "Ücretsiz" veya "0 TL" olarak girmek zorundasınız. Açıklamaya "Ücretli" yazanların ilanları onaylanmaz.
İş İlanları, İŞKUR Mevzuatı ve Yurt Dışı İstihdam:
1. Lisans Zorunluluğu: Tatildesen üzerinden "Özel İstihdam Bürosu" sıfatıyla ilan giren veya işçi-işveren aracılığı yapan Kurumsal Üyeler, 4904 sayılı Kanun gereği İŞKUR'dan aldıkları "Özel İstihdam Bürosu İzin Belgesi"numarasını ilanda belirtmek zorundadır. Belgesiz aracılık faaliyetleri yasaktır.
2. Yurt Dışı İstihdam: İŞKUR'dan alınmış özel izin ve onaylı talep dilekçesi olmaksızın; "Yurt dışına işçi götürülür", "Vize garantili iş", "Almanya'da çalışma izni" gibi vaatler içeren ilanlar girilemez. Bu tür illegal faaliyet şüphesi taşıyan ilanlar derhal silinir ve savcılığa bildirilir.
3. Kendi Personelini Arama: Kendi işletmesi için personel arayan firmalar (aracı olmayanlar), İŞKUR belgesi olmaksızın ilan verebilir ancak "Yurt dışı" veya "Komisyonla iş bulma" faaliyeti yürütemezler.
 
 
4.4. Dolandırıcılığı Önleme ve Güvenlik Politikası
Ödeme işlemleri yalnızca Tatildesen’in sunduğu güvenli ödeme sistemleri (İyzico vb.) aracılığıyla yapılmalıdır.İlansahipleri, kullanıcılar ile güvenli mesajlaşma sistemi üzerinden iletişim kurmalıdır.Tatildesen, sahtekarlık veya dolandırıcılık şüphesi taşıyan ilanları askıya alma, inceleme başlatma ve yasal makamlara bildirme hakkına sahiptir.
Zincirleme Hesap Kapatma : Tatildesen, bir Kurumsal Üye'nin veya Yetkili Kullanıcı'nın işbu Sözleşme'ye, İlan Verme Kuralları'na veya genel güvenlik politikalarına aykırı davrandığını tespit etmesi halinde; sadece ihlali gerçekleştiren hesabı değil, bu hesapla ilişkili olduğu teknik veya idari verilerle (Aynı Vergi Kimlik No, T.C. Kimlik No, telefon numarası, IP adresi, cihaz kimliği/MAC adresi veya fatura bilgileri) tespit edilen diğer tüm hesapları (Bireysel veya Kurumsal ayrımı yapmaksızın) herhangi bir ön bildirimde bulunmaksızın kapatma, durdurma veya askıya alma hakkına sahiptir. Üye, bu tür "ilişkili hesap" kapatma işlemleri nedeniyle Tatildesen'dan herhangi bir tazminat veya hak talep edemez.
Mesajlaşma Denetimi ve Filtreleme: Kurumsal Üye, Tatildesen üzerinden gerçekleştirdiği mesajlaşmaların özel iletişimden ziyade "ticari iletişim" niteliğinde olduğunu kabul eder. Tatildesen; dolandırıcılığı önlemek, kara para aklama şüphesini gidermek, hakaret/küfür içeren veya yasadışı ticarete konu (silah, uyuşturucu vb.) yazışmaları engellemek amacıyla; mesaj trafiğini otomatik güvenlik yazılımları ve algoritmalarla tarama, filtreleme, sakıncalı içerikleri (IBAN, telefon numarası, yönlendirici link vb.) maskeleme veya mesajı iletmeme hakkına sahiptir. Üye, bu güvenlik taramalarının haberleşme gizliliğini ihlal etmediğini, platform güvenliği için zaruri olduğunu peşinen kabul eder.
4.5. İlan Denetim ve Yayın Süreci
İlanlar, tatildesen ekibi tarafından manuel ve otomatik (yapay zeka) denetim süreçlerinden geçmektedir. Denetimler sırasında, ilan içeriğinde uygunsuzluk tespit edilirse ilan reddedilir veya düzeltme talep edilir. İlan onay süreci ortalama 24 saat içerisinde tamamlanır. İlan sahibi, ilanı düzenleyerek eksiklikleri giderme hakkına sahiptir. İlan kullanıcı tarafından tekrar düzenlenmesinin ardından firmamızca incelenerek yayına alınır. Her ilan, kategori fark etmeksizin aynı doğrulama sürecine tabidir.
4.6 ŞÜPHELİ İŞLEMLER VE GÖRÜNÜRLÜK KISITLAMASI 
Tatildesen, tamamen kendi takdirinde olmak üzere; şüpheli işlem yapan, spam/tekrarlayan içerik giren, sistem açıklarını zorlayan veya topluluk kurallarını ihlal etme eğilimi gösteren Üyelerin; üyeliklerini tamamen iptal etmeksizin ilanlarının görünürlüğünü azaltma, arama sonuçlarında en alt sıralara düşürme veya belirli özelliklere (mesajlaşma, doping kullanımı vb.) erişimini geçici veya kalıcı olarak kısıtlama hakkını saklı tutar. Üye, bu tür 'Görünürlük Kısıtlamaları' nedeniyle herhangi bir ücret iadesi, süre uzatımı veya tazminat talep edemez.
5. KATEGORİ YÖNETİMİ VE ALGORİTMA YETKİSİ 
Tatildesen, tamamen kendi takdirine bağlı olarak; Platform üzerindeki kategori yapısını, sınıflandırmaları ve hizmet başlıklarını dilediği zaman önceden bildirmeksizin değiştirebilir. İlanların sıralanması, görüntülenme sıklığı ve arama sonuçlarındaki yeri, Tatildesen'ın mülkiyetinde olan ve ticari sır niteliği taşıyan dinamik algoritmalara dayanır. Üye, organik arama sonuçlarında neden üstte veya altta yer aldığına dair Tatildesen'dan herhangi bir teknik açıklama, ifşa veya tazminat talep edemez.
6. Hizmet Bedelleri ve Ödeme Koşulları
Kurumsal Üyeler, Mağaza açma, ilan yayınlama ve diğer hizmetlerden yararlanma bedellerini Tatildesen’in belirlediği ücretlendirme politikalarına uygun olarak ödemekle yükümlüdür. Ödemeler İyzico veya Tatildesen’in belirlediği diğer güvenli ödeme yöntemleri aracılığıyla gerçekleştirilecektir. Üyelik ücreti veya hizmet bedeli ödenmediği takdirde, Tatildesen hizmetleri askıya alma hakkına sahiptir.
 
7. HİZMET GARANTİSİ YOKLUĞU (AS IS) 
Tatildesen, Platform hizmetlerini 'Olduğu Gibi' (As Is) sunmakta olup; hizmetlerin kesintisiz, hatasız, mükemmel olduğu veya Kullanıcı'nın ticari ihtiyaçlarını/beklentilerini tam olarak karşılayacağı taahhüdünde bulunmaz. Yazılım güncellemeleri, teknik arızalar, siber saldırılar, veri merkezi sorunları veya altyapı çalışmaları nedeniyle oluşacak kesintilerden, veri kayıplarından veya ticari zararlardan Tatildesen sorumlu tutulamaz.
8. BAKIM VE ERİŞİM KISITI
 Tatildesen, sisteme ilişkin iyileştirme, güncelleme, bakım veya yenileme çalışmaları nedeniyle Platform'a erişimin geçici olarak durması veya yavaşlaması hallerinden sorumlu değildir. Kullanıcı, bu tür planlı veya zorunlu bakım çalışmaları süresince hizmet verilememesi nedeniyle herhangi bir hak, tazminat veya ilan süresi uzatımı talep edemeyeceğini peşinen kabul eder.
9. Mücbir Sebep
Tarafların kontrolü dışında gelişen doğal afetler, savaş, salgın hastalıklar, altyapı sorunları, siber saldırılar, hizmet sağlayıcı kesintileri gibi sebeplerden dolayı yükümlülüklerin yerine getirilememesi halinde, taraflar sorumlu tutulamaz.Tatildesen, dış kaynaklı siber saldırılar, DDOS, veri sızdırma girişimleri gibi durumlarda hizmet kesintisinden sorumlu tutulamaz.
10. Uygulanacak Hukuk ve Yetki
Bu Sözleşme, Türkiye Cumhuriyeti yasalarına tabidir. Sözleşmeden kaynaklanabilecek ihtilaflarda Ankara Mahkemeleri ve İcra Daireleri yetkilidir.
Delil Sözleşmesi: Taraflar, işbu Sözleşme’den doğabilecek her türlü ihtilafta; Tatildesen'ın kendi veritabanında, sunucularında tuttuğu elektronik kayıtların, sistem loglarının, ticari defterlerin, e-posta yazışmalarının ve bilgisayar kayıtlarının;  HMK Madde 193 uyarınca bağlayıcı, kesin ve münhasır delil teşkil edeceğini ve bu maddenin bir Delil Sözleşmesi niteliğinde olduğunu kabul, beyan ve taahhüt eder.
TEBLİGAT VE BİLDİRİM ESASLARI 
Üye'nin Tatildesen.com sistemine kayıt olurken bildirdiği veya sonradan güncellediği e-posta adresi, telefon numarası ve KEP (Kayıtlı Elektronik Posta) adresi, yasal tebligat adresi olarak kabul edilir. Tatildesen tarafından bu kanallara yapılan tüm bildirimler, doğrulama kodu gönderimleri, ihtarlar ve bilgilendirmeler; gönderildiği andan itibaren Üye'ye ulaşmış ve hukuken tebliğ edilmiş sayılır. İletişim bilgilerini güncel tutmak ve e-posta kutusunu düzenli kontrol etmek tamamen Üye'nin sorumluluğundadır.
11. Fiyatlandırma ve Ücret Politikası
11.1 Ücretli Hizmetler
Tatildesen.com platformunda sunulan ücretli boost servisleri ve ilan fiyatlandırma politikası, çağrı merkezi tarafından beyan edilen ücretler, hizmetin satın alındığı tarihte geçerli olan tutar üzerinden tahsil edilmektedir. Bakım ve teknik kesintiler bu süreye dahildir, süre uzatımı yapılmaz. Tek seferlik alınan ilan 30/60/90/180 gün veya 365 günlük hangi paketi satın aldıysa, seçilen paket süresince  yayında kalır, 30 günün sonunda kullanıcı ilanı yenilemek isterse yeniden ilan satın almalıdır. Boost paketleri kullanım süresi 1 haftadır ve tek ilan için kullanılabilir, kullanıcı her ilan için ayrı Boost paketi satın almalıdır. Satın alınan 'Vitrin/Boost' hizmetleri, ilanın 7/24 sabit bir pozisyonda veya en üst sırada kalacağını garanti etmez. İlanın sıralaması; anlık site trafiğine, diğer ilanların yoğunluğuna, algoritmik puanlamaya ve rotasyon kurallarına göre değişkenlik gösterebilir. Doping/Boost Transfer Yasağı: Satın alınan Doping/Boost hizmeti, sadece uygulandığı ilan kimliği (ID) için geçerlidir. Dopingli bir ilanın içeriği, markası, modeli veya temel niteliği değiştirilerek başka bir ürüne dönüştürülemez. Doping hakkı başka bir ilana devredilemez, taşınamaz veya bölünemez. İlan, kullanıcı tarafından yayından kaldırılsa veya Tatildesen tarafından askıya alınsa bile Doping süresi işlemeye devam eder, süre dondurulamaz. Taahütsüz paket kullanmak istenirse fiyatlandırma taahhütlü fiyat x2 /Ay olarak fiyatlandırılır. Örneğin 15 li ilan paketi taahhütlü 2500 TL, Taahhütsüz 5.000 TL
Sıralama ve Algoritma Garantisi Yokluğu: Tatildesen, platform üzerindeki arama sonuçlarının sıralamasını, vitrin ilanlarının gösterim sıklığını ve algoritmik yapıyı tek taraflı olarak belirleme ve değiştirme hakkına sahiptir. Ücretli "Doping" hizmeti satın alan Üye, ilanın sadece görünürlüğünün artırıldığını; ancak rakiplerin de benzer hizmeti alması durumunda sistemin "Rastgele" (Random) veya "Sıralı Rotasyon" yöntemini işleteceğini kabul eder. Anlık ekran görüntüleri (Screenshot) alınarak "İlanım en üstte değil" şikayetiyle yapılan iade talepleri, teknik işleyişe aykırı olduğu için reddedilir.
11.2 Ücret Değişiklikleri
tatildesen, hizmet bedellerinde değişiklik yapma hakkını saklı tutar. Fiyatlar çağrı merkezi veya tatildesen.com üzerinden iletişim yoluyla beyan edilir.
11.3 Tahhütlü Hizmetlerde İptal ve Ücretlendirme
Kullanıcı tarafından taahhütlü bir hizmetin erken iptal edilmesi durumunda, iptalin gerçekleştiği tarih itibarıyla kullanılmış aylar veya kalan taahhüt süresi göz önünde bulundurularak, talep edilecek aylık indirim veya fayda tutarı, kullanıcının lehine olacak şekilde hesaplanır ve firmamız tarafından tahsil edilir. İptal talebi, kullanıcının başvurusunun ardından 7 iş günü içerisinde işleme alınır ve varsa bakiye borç tutarı kullanıcıya yazılı olarak bildirilir.
11.4 Fatura ve Ödeme
Tüm ücretli hizmetler, faturalandırma sürecine tabidir ve kullanıcıya elektronik ortamda gönderilir.Ödemeler, platformda belirtilen ödeme yöntemleri (kredi kartı, sanal POS vb.) aracılığıyla yapılır. Ödemelerin düzenli olarak yapılmaması halinde, hizmet askıya alınabilir veya iptal edilebilir.
11.5. Otomatik Yenileme ve Tahsilat Talimatı 
Kurumsal Üye, satın aldığı Mağaza, İlan Paketi veya düzenli ödeme gerektiren diğer abonelik hizmetlerinin; iptal talimatı verene kadar her yenileme döneminde (seçilen plana göre aylık veya yıllık) otomatik olarak yenileneceğini kabul eder. Üye, yenileme tarihindeki güncel paket ücretinin, sisteme tanımladığı kredi kartından veya ödeme aracından Tatildesen tarafından otomatik olarak tahsil edilmesine gayrikabili rücu (geri dönülemez) onay verir. Kart limitinin yetersiz olması veya tahsilat yapılamaması durumunda hizmet askıya alınabilir.
12. Ödeme Entegrasyonu 
Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır. Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder. Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
13. Hizmetlerde İptal ve Ödeme Süreci Aylık ödeme planına sahip hizmetlerde, kullanıcı iki ay üst üste ödeme yapmadığı takdirde, hizmet askıya alınır.Bu durumda, kalan taahhüt süresinin toplam bedeli tahsil edilir ve kullanıcı, ön ödemeli hizmet modeline geçirilir.Ön ödemeli sistemde, kullanıcı bir sonraki dönem için ödeme yapmadan hizmetten yararlanamaz.
Taahhütlü Hizmetlerde İlan Yayında Kalma Süresi:
Kullanıcının taahhütlü bir aboneliği varsa ve ilanı yayından kaldırmazsa, ilan bir sonraki ayda da yayında kalmaya devam eder.Bu durumda, ilanın yayında kaldığı yeni ay, yenilenen ilan yükleme kredisinden düşülür. Eğer kullanıcının taahhüdü yoksa ve ilan yayınlama paket ücreti ödenmezse, ilan yayından
kaldırılır. 
14. İlan Yayından Kaldırılma ve Askıya Alma Süreci
Tatildesen.com olarak, ilanların doğru, eksiksiz ve güncel bilgiler içermesi gerektiğine önem vermekteyiz. Bu nedenle aşağıdaki durumlarda ilanı askıya alma veya yayından kaldırma hakkımız saklıdır:
İlanın Gerçeği Yansıtmaması veya Yanıltıcı Bilgi İçermesi:
İlan içeriğinde yanıltıcı, eksik, yanlış veya gerçeği yansıtmayan bilgiler bulunması.İlan görselleri veya videolarının ürün/hizmetle uyumsuz olması veya manipüle edilmiş olması.
Fiyatlandırma Problemleri:
Ürün veya hizmet fiyatının, piyasa değerine göre fahiş şekilde düşük veya yüksek olarak belirlenmesi. İlanın, fiyat spekülasyonu oluşturacak nitelikte düzenlenmesi. İlan fiyatının tarihlere göre değişkenlik gösterdiği ilanlarda güncel fiyatın girilmemesi.
Görsel ve Video Uygunsuzlukları:
İlan görselleri veya videolarında yanıltıcı, manipüle edilmiş veya gerçek dışı içeriklerin yer alması.Üçüncü şahıs haklarını ihlal eden görsellerin kullanılması,konum ve verilen hizmetlerin bilgisinin veya özelliklerin hatalı girilmesi
Şikayet ve Bildirimler:
 
İlan hakkında yapılan şikayetler doğrultusunda yapılan incelemelerde uygunsuzluk veya gerçeği yansıtmama tespit edilmesi. Kullanıcı geri bildirimleri ve üçüncü taraf doğrulamaları ile tespit edilen hatalar.
Tatildesen.com, yukarıda belirtilen durumlarda ilanı askıya alma, yayından kaldırma veya düzenleme talep etme hakkına sahiptir. İlan sahibi, düzeltme yapmadığı sürece ilan tekrar yayına alınmayabilir.
Arama Motoru İndeksleri ve Cache Kayıtları İlanın yayından kaldırılması, süresinin dolması veya üyeliğin silinmesi durumunda; Tatildesen sistemlerindeki veri anında pasife alınır. Ancak, Google, Yandex, Bing vb. arama motorlarının önbelleklerinde (cache) veya arama sonuçlarında yer alan verilerin güncellenmesi veya silinmesi Tatildesen'ın teknik kontrolü dışındadır. Tatildesen, üçüncü taraf arama motorlarının veritabanlarında kalan eski kayıtlardan sorumlu tutulamaz. Üye, kişisel veya ticari verilerinin arama motoru indekslerinden silinmesi taleplerini doğrudan ilgili arama motorunun "İçerik Kaldırma" araçları üzerinden ileteceğini kabul eder.
MARKA KULLANIMI VE İTİBAR KORUMA 
Kurumsal Üye, Tatildesen.com logosunu, ticari unvanını veya markasını yazılı izin olmaksızın hiçbir mecrada (kartvizit, tabela, web sitesi vb.) kullanamaz; kendisini Tatildesen'ın iş ortağı, acentesi veya yetkili temsilcisi gibi gösteremez. ayrıca, Platform, yöneticileri veya ticari faaliyetleri hakkında sosyal medya, sözlükler, şikayet siteleri veya diğer dijital mecralarda; gerçeğe aykırı, haksız rekabet yaratan, hakaret içeren veya ticari itibarı zedeleyici beyanlarda bulunmamayı; aksi takdirde üyeliğinin tazminatsız feshedileceğini ve Tatildesen'in maddi/manevi tazminat haklarının saklı olduğunu kabul ve taahhüt eder.
15. Yürürlük
Kurumsal Üye, bu Sözleşme ve eklerinde belirtilen tüm şartları elektronik ortamda onaylayarak kabul ettiğini beyan eder. Sözleşme, onay tarihi itibariyle yürürlüğe girer.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızın derhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN BÖLÜNEBİLİRLİĞİ 
İşbu Sözleşme’nin herhangi bir hükmünün, yetkili bir mahkeme veya idari makam tarafından geçersiz, mevzuata aykırı veya uygulanamaz ilan edilmesi halinde; bu durum Sözleşme’nin diğer hükümlerinin geçerliliğini ve bağlayıcılığını etkilemeyecek, geriye kalan hükümler aynen yürürlükte kalarak tarafları bağlamaya devam edecektir.
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: 
Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: 
Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'ın onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
TATİLDESEN.COM KİŞİSEL VERİLERİN KORUNMASI VE İŞLENMESİ HAKKINDA AYDINLATMA METNİ
1. Veri Sorumlusu ve Temsilcisi 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) uyarınca, kişisel verileriniz, veri sorumlusu sıfatıyla tatildesen.com (“Şirketimiz”) tarafından aşağıda açıklanan kapsamda işlenebilecektir.
Ticari Ünvan: Tatildesen  Merkez Adresi: KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN  
2.İşlenen Kişisel Veriler 
Kurumsal kullanıcılarımızdan aşağıdaki kişisel veriler işlenebilmektedir:
Kimlik ve İletişim Bilgileri: Ad, soyad, T.C. kimlik numarası, doğum tarihi, telefon, e-posta, adres, şirket telefonu, il, ilçe.Ticari ve Vergi Bilgileri: Vergi kimlik numarası, vergi dairesi, fatura bilgileri, imza sirküleri, vergi levhası.Kimlik Doğrulama ve Onay Bilgileri: Kimlik fotokopisi, imzalı metin, "Okudum, anladım, onaylıyorum" ifadesi ile birlikte ad, soyad, imza sürecinde kimlik sahibinin yüz öz çekim resmi.İşletme ve Mağaza Bilgileri: Mağaza görseli, profil fotoğrafı.Ödeme Bilgileri: Kart bilgileri doğrudan saklanmaz, anlaşmalı sanal POS ödeme aracı tarafından işlenir, ödeme aracı tarafının hüküm ve koşulları geçerlidir.
Ticari Elektronik İleti ve İYS Onayı: 
Üye, Tatildesen.com'a üye olurken veya hizmet alırken paylaştığı iletişim bilgilerine (cep telefonu, e-posta adresi); Tatildesen ve yetkili iş ortakları tarafından kampanya, promosyon, indirim, tanıtım, anket, pazar araştırması ve bilgilendirme amacıyla Ticari Elektronik İleti (SMS, E-posta, MMS, Otomatik Arama vb.) gönderilmesine, verilerinin bu amaçla işlenmesine, saklanmasına ve mevzuat gereği İYS'ye (İleti Yönetim Sistemi)aktarılmasına 6563 sayılı Kanun kapsamında açıkça onay verdiğini kabul ve beyan eder. Üye, dilediği zaman, hiçbir gerekçe göstermeksizin ticari elektronik ileti almayı reddetme (iptal etme) hakkına sahiptir.
3. Kişisel Verilerin İşlenme Amaçları Toplanan kişisel verileriniz, aşağıdaki amaçlarla işlenmektedir:
Kullanıcı hesaplarının oluşturulması ve yönetimi. İlan verme, ilan arama ve görüntüleme hizmetlerinin sunulması.Satıcı ve alıcı arasındaki iletişimin sağlanması. Dolandırıcılık  ve sahte ilanların önlenmesi. Güvenli e-ticaret hizmetlerinin yürütülmesi.Kullanıcı deneyiminin iyileştirilmesi.Yasal yükümlülüklerin yerine getirilmesi .Kullanıcılara özel kampanya ve pazarlama faaliyetlerinin yürütülmesi.
Bu işleme faaliyetleri KVKK Madde 5/2(a, c, ç, e, f) ve Madde 6/2 kapsamında işlenmektedir.
4. Kişisel Verilerin Kimlere ve Hangi Amaçla AktarılabileceğiKişisel verileriniz, KVKK’nın 8. ve 9. maddeleri kapsamında aşağıdaki kişi ve kuruluşlarla paylaşılabilir:
Kişisel verileriniz, yalnızca resmi kurum ve yetkili makamların yazılı talebi ile paylaşılacaktır. Dolandırıcılık ve güvenlik tedbirleri kapsamında iş ortaklarımız. Ödeme hizmeti sağlayıcıları ve bankalar. Sunucu, barındırma ve veri depolama hizmeti veren firmalar. Kullanıcının açık rızası bulunması halinde reklam ve pazarlama faaliyetleri için iş ortaklarımız.
Kredi/Banka kartı bilgisi ödeme aracısı sistem için aktarılır; Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır. Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder. Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
İletişim Güvenliği: 
Platform içi mesajlaşma içeriklerinin; suç gelirlerinin aklanmasının önlenmesi, dolandırıcılık tespiti ve kullanıcı güvenliğinin sağlanması amacıyla otomatik filtreleme sistemleri ile işlenmesi ve şüpheli durumların ilgili adli makamlara bildirilmesi.
5. Kişisel Verilerin Saklama Süresi
Kişisel verileriniz, ilgili mevzuatta belirtilen süreler boyunca saklanmaktadır:
Hesap bilgileri: Kullanıcı hesabı aktif olduğu sürece saklanır.İşlem kayıtları: 5651 sayılı Kanun gereği 2 yıl boyunca saklanır.Fatura ve finansal kayıtlar: 213 sayılı Vergi Usul Kanunu gereği 5 yıl boyunca saklanır.
Tatildesen.com veritabanından silinen kişisel veriler, üçüncü taraf arama motorlarının (Google vb.) önbelleklerinde bir süre daha erişilebilir olabilir. Bu süreç Tatildesen'ın veri sorumluluğu alanının dışındadır.
Üyelik sözleşmesinde belirtilen "Pasif Hesap" kriterlerine uyan ve 6 aydan uzun süre işlem görmeyen hesaplara ait kişisel veriler; yasal saklama zorunluluğu (log kayıtları vb.) bulunanlar hariç olmak üzere, periyodik veri imha süreçlerinde anonimleştirilir veya silinir.
6. Çerezler ve Yurt Dışına Veri Aktarımı
Web sitemizde kullanılan çerezler aracılığıyla Google, Meta (Facebook, Instagram), Amazon Web Services (AWS), Microsoft, Apple gibi yurt dışındaki hizmet sağlayıcılarla sınırlı ölçüde veri paylaşımı yapılabilmektedir. Bu paylaşım, reklam, pazarlama, analitik çalışmalar ve kullanıcı deneyiminin iyileştirilmesi amacıyla gerçekleştirilmektedir. Bu kapsamda yalnızca anonimleştirilmiş veriler işlenmekte olup, kimliği doğrudan belirleyici kişisel veriler aktarılmamaktadır. Kullanıcılar, çerez tercihlerini tarayıcı ayarları üzerinden değiştirebilirler.
İlan görselleri ve videoları (araç ve emlak ilanlarına ait olanlar) kişisel veriler hariç olmak üzere yalnızca görseller, yurt dışı sunucularımıza veya hizmet sağlayıcılarına (örneğin, Amazon Web Services vb.) aktarılabilir.
Kişisel veriler yurt dışına aktarılmamaktadır.
7. Meşru Menfaat Kapsamında Kişisel Veri İşleme KVKK’nın 5/2-f maddesi uyarınca, tatildesen.com’un meşru menfaati çerçevesinde aşağıdaki durumlarda kişisel veriler işlenebilir:
Kullanıcı güvenliğini sağlamak ve dolandırıcılığı önlemek. Kullanıcılara yönelik hizmetlerin geliştirilmesi ve özelleştirilmesi. Platformun güvenliğini sağlamak ve teknik sorunları gidermek. Mevcut müşteri ilişkilerinin yönetimi. Kullanıcının yasal haklarının korunması. Kullanıcının onayı olmadan reklam ve pazarlama faaliyetleri yürütülmez. Ancak, mevcut kullanıcılarımızın meşru menfaatler kapsamında hizmetlerinden en iyi şekilde faydalanması için analitik değerlendirmeler yapılabilir.
8. Kişisel Veri Toplama Yöntemi ve Hukuki Sebebi Verileriniz, web sitesi, mobil uygulama, müşteri hizmetleri, çağrı merkezi, çerezler, sosyal medya kanalları ve iş ortaklarımız aracılığıyla KVKK’nın 5. ve 6. maddelerine uygun olarak toplanmaktadır.
9. Veri Sahibi Olarak Haklarınız KVKK’nın 11. maddesi kapsamındaki haklarınız şunlardır:
Kişisel verilerinizin işlenip işlenmediğini öğrenme.İşlenen verilerinizle ilgili bilgi talep etme.Yanlış veya eksik işlenmiş verilerin düzeltilmesini talep etme.Verilerin silinmesini veya yok edilmesini isteme.Kişisel verilerinizin üçüncü kişilere aktarılıp aktarılmadığını öğrenme.Hukuka aykırı veri işleme nedeniyle zarara uğradıysanız tazminat talep etme.
Bu haklarınızı kullanmak için KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN   adreslerine Noter kanalıyla başvuru yapılabilir.
10. Aydınlatma Metninde Değişiklik Yapılması tatildesen.com, hizmetleri ve mevzuat değişikliklerine bağlı olarak bu metni güncelleme hakkını saklı tutar. Güncellenmiş metin, web sitesi ve mobil uygulama üzerinden yayımlanarak yürürlüğe girecektir.
 
 
İLAN VERME KURALLARI
1. Genel Kurallar
İlan veren, mevzuata, Tatildesen.com ilan verme kurallarına ve Üyelik Sözleşmesine uygun hareket etmeyi kabul eder. Tüm üyeler ve tüm ilanlar kategorileri için 1 ilanın yayın süresi 30 gündür. İlan içeriğinde yanıltıcı, aldatıcı veya gerçeğe aykırı beyanlar bulunamaz. Aynı ürün/hizmet için birden fazla ilan açmak yasaktır. Mükerrer ilanlar yayından kaldırılabilir. İlan başlığı ve açıklaması sadece ilan konusu ile ilgili bilgiler içermelidir. Reklam içerikli ifadeler, linkler veya alakasız bilgiler eklenemez. Ürün veya hizmetin gerçek ve güncel fiyatı belirtilmelidir. Gerçeğe aykırı fiyat yazılamaz. Piyasa değerinden aşırı düşük veya aşırı fazla ilanlar incelemeye alınabilir ve yayından kaldırılabilir. Aynı ürünü, sadece tarihini güncellemek veya öne çıkarmak için silip yeniden yüklemek yasaktır. Bu işlem sistem tarafından engellenir ve ısrarı halinde hesap kısıtlanır. İlanı öne çıkarmak için "Doping" seçenekleri kullanılmalıdır.
'Hizmetler' kategorisinde profil oluşturan veya ilan veren Kurumsal Üye (Nakliye Firması, Usta, Temizlik Şirketi vb.), Tatildesen'den tamamen bağımsız bir ticari işletme/yüklenicidir. Tatildesen, bu kategoride sunulan hizmetin kalitesi, zamanlaması, güvenliği, ayıplı olması veya eksik ifası konusunda hiçbir garanti vermez ve taraf değildir. Hizmet alan kullanıcı ile Hizmet veren Üye arasında doğacak uyuşmazlıklarda, maddi/manevi zararlarda veya iş kazalarında; Tatildesen'ın hukuki veya cezai hiçbir sorumluluğu bulunmamaktadır. Üye, müşterisiyle yaşadığı sorunları Tatildesen'a yansıtamayacağını kabul eder.
2. Yasaklı ve Kısıtlı İçerikler
Telif hakkı, marka hakkı veya fikri mülkiyet haklarını ihlal eden içerikler yasaktır.Her türlü müstehcen, pornografik, nefret söylemi içeren veya terör propagandası yapan ilanlar kaldırılır. Dolandırıcılığa yol açabilecek veya aldatıcı beyan içeren ilanlar yasaktır. Yasalar gereği satışı yasaklanmış ürünler platformda yayınlanamaz. (Örnek: Tütün ürünleri, ilaçlar, sahte belgeler vb.)Yasaklı ve kısıtlı içeriklerin paylaşımından kaynaklanacak her türlü hukuki ve cezai sorumluluk tamamen ilan verene aittir. Bu tür ilanların paylaşımı halinde sorumlu ve muhatap doğrudan ilan veren kullanıcıdır. Tatildesen, yasaklı ürünler listesini güncelleme ve ilanları denetleme hakkına sahiptir. Tescilli markaların (Örn: Nike, Adidas, Gucci, Rolex, Apple vb.) taklitleri, logolu kopyaları, replikaları veya "Benzeri" adı altında satılan ürünlerin ilana koyulması kesinlikle yasaktır. "Orijinalinden farksız" yazsanız dahi ilanınız silinir.
Yönlendirme ve Spam Yasağı: Üye, diğer kullanıcılara; reklam, tanıtım, zincirleme mesaj, "Kolay para kazanma" teklifleri veya rakip sitelerin linklerini içeren spam mesajlar gönderemez. Tatildesen mesajlaşma sistemi, kullanıcıları site dışına çekmek veya illegal platformlara (bahis, kripto vb.) yönlendirmek için kullanılamaz. Sistem algoritmaları bu tür içerikleri tespit ettiğinde mesajı engeller ve hesabı kapatır.
3. İlan İçeriği ve Görsel Kullanımı
İlan görselleri ve videoları, yalnızca ilgili ürün/hizmetle doğrudan bağlantılı olmalıdır. Temsili veya başka kaynaklardan alınan görseller kullanılamaz.İlan görselleri ve videoları ilan konusu taşınmaza veya ürüne ait olmalıdır, başka projelerden veya temsil amaçlı olmamalıdır. Görsellerde firma logoları, telefon numarası, web sitesi adresi veya sosyal medya hesapları yer alamaz.İlan açıklaması, ürün veya hizmetin tüm detaylarını içermeli, yanıltıcı bilgi barındırmamalıdır. Manipüle edilmiş, yanlış bilgi içeren, görsel montaj ile yanıltıcı hale getirilmiş ilanlar yayından kaldırılır.Tatildesen.com platformunda yer alan ilanlara ilişkin açıklama metinleri, ilan sahibi kullanıcı tarafından beyan edilen araç bilgileri esas alınarak, sistem tarafından otomatik olarak oluşturulmaktadır. Bu otomatik açıklamalar, kullanıcının sağladığı marka, model, yıl, paket, donanım ve benzeri teknik bilgiler doğrultusunda yapay zeka destekli sistem aracılığıyla oluşturulmakta olup, bilgilendirme amacı taşır.
İlan açıklamasının doğruluğunun ve yasal uygunluğunun kontrol ve düzenleme sorumluluğu tamamen ilan sahibine aittir. Kullanıcı, platform tarafından oluşturulan açıklamaları kontrol etmekle yükümlü olup, gerektiğinde düzeltme yapabileceğini kabul eder. Tatildesen.com, kullanıcı tarafından sağlanan eksik, yanlış veya yanıltıcı bilgi sebebiyle ortaya çıkabilecek herhangi bir doğrudan ya da dolaylı zarardan sorumlu değildir.
Kullanıcı, beyan ettiği tüm bilgilerin gerçeğe uygun olduğunu ve üçüncü kişi haklarını ihlal etmediğini taahhüt eder. Aksi takdirde doğacak her türlü hukuki ve cezai sorumluluk kendisine aittir.
4. Emlak İlanları İçin Özel Kurallar
Tapu ve Ruhsat Bilgileri: Emlak ilanlarında, taşınmazın tapu kaydı, ruhsat durumu ve iskan bilgisi doğru girilmelidir. Komisyon ve Yetkilendirme: Yetkisiz emlakçılar ilan veremez, yetki belgesi olmayan aracılar yasaktır. Kiralamalar: Kiralık ilanlarda minimum ve maksimum sözleşme süresi belirtilmelidir. Fiyat Doğruluğu: Kira veya satış bedeli yanlış girilemez. Piyasa değerinden aşırı düşük veya aşırı fazla ilanlar incelenir ve gerekirse yayından kaldırılır. EIDS Süreci: İlan sahibi veya yetkili kişi tarafından girilen ilan bilgilerinin, EIDS sistemi tarafından doğrulanan sahiplik bilgileriyle uyuşması zorunludur. Uyuşmazlık tespit edilirse ilan yayından kaldırılabilir.
E-İlan Doğrulama (EIDS) ve Para Birimi (32 Sayılı Karar): 
Üye, Gayrimenkul ve Araç ilanlarında Ticaret Bakanlığı mevzuatı gereği E-Devlet üzerinden Kimlik ve Yetki Doğrulaması (EIDS) yapmak zorundadır. Yetki belgesi olmayan veya doğrulanmamış ilanlar yayınlanmaz. Yanıltıcı beyanla girilen veya EIDS kurallarına aykırı ilanlardan doğacak her türlü idari para cezasından (Bakanlık cezaları dahil) doğrudan Üye sorumludur; Tatildesen bu cezaları Üye'ye rücu eder. Ayrıca, 32 Sayılı Karar uyarınca; Türkiye'de yerleşik kişilerin menkul ve gayrimenkul satış/kiralama ilanlarında fiyatların Türk Lirası (TL) olarak girilmesi zorunludur. Döviz cinsinden girilen ilanlar reddedilir.
Turizm Amaçlı Konut Kiralama (7464 Sayılı Kanun): 1. İzin Belgesi Zorunluluğu: 7464 sayılı 'Konutların Turizm Amaçlı Kiralanması Hakkında Kanun' uyarınca; 100 gün ve altındaki sürelerle konut kiralaması (Günlük/Haftalık Kiralık) yapan Kurumsal Üye; T.C. Kültür ve Turizm Bakanlığı’ndan alınmış "Turizm Amaçlı Konut İzin Belgesi"ne sahip olmak ve bu belgeyi Tatildesen'a ibraz etmek zorundadır. Belgesi olmayan konutlar için 100 günden kısa süreli kiralama ilanı girilemez. Konaklayan misafirlerin kimlik bilgilerinin Emniyet/Jandarma'ya bildirilmesi (KBS/GIYKIMBIL) yükümlülüğü tamamen Üye'ye aittir. Bu yükümlülüklerin ihlali veya belgesiz ilan girişi nedeniyle Tatildesen’a kesilebilecek her türlü idari para cezası, ferileriyle birlikte Üye'ye rücu edilir. Tatildesen, Üye tarafından sisteme girilen 'İzin Belgesi Numarası'nın veya yüklenen belgelerin doğruluğunu, geçerliliğini ve güncelliğini araştırmakla yükümlü değildir. Sistem, Üye'nin beyanını esas alır. Üye'nin sahte, geçersiz, başkasına ait veya iptal edilmiş bir izin belgesi numarası girerek **'Yanıltıcı Beyan'**da bulunması; sistemi ve potansiyel kiracıları kandırması durumunda tüm hukuki ve cezai sorumluluk münhasıran Üye'ye aittir. Bu nedenle Tatildesen'a herhangi bir idari para cezası (Bakanlık cezaları) kesilmesi veya Tatildesen'ın üçüncü kişilere tazminat ödemesi halinde; söz konusu tutarlar ferileriyle birlikte Üye'ye rücu edilir (yansıtılır).
 
E-İlan Doğrulama (EIDS) ve Para Birimi (32 Sayılı Karar): 
Üye, Gayrimenkul ve Araç ilanlarında Ticaret Bakanlığı mevzuatı gereği E-Devlet üzerinden Kimlik ve Yetki Doğrulaması (EIDS) yapmak zorundadır. Yetki belgesi olmayan veya doğrulanmamış ilanlar yayınlanmaz. Yanıltıcı beyanla girilen veya EIDS kurallarına aykırı ilanlardan doğacak her türlü idari para cezasından (Bakanlık cezaları dahil) doğrudan Üye sorumludur; Tatildesen bu cezaları Üye'ye rücu eder. Ayrıca, 32 Sayılı Karar uyarınca; Türkiye'de yerleşik kişilerin menkul ve gayrimenkul satış/kiralama ilanlarında fiyatların Türk Lirası (TL) olarak girilmesi zorunludur. Döviz cinsinden girilen ilanlar reddedilir.
 KİRALIK ARAÇ (RENT A CAR) İLANLARI İÇİN ÖZEL KURALLAR
1. KABİS ve Ruhsat Zorunluluğu: Araç kiralama ilanı veren Kurumsal Üye; Emniyet Genel Müdürlüğü Kiralık Araç Bildirim Sistemi'ne (KABİS) kayıtlı olduğunu, araçları kiralayan kişilerin kimlik bilgilerini bu sisteme anlık olarak işleyeceğini ve yasal "Rent a Car" işletme ruhsatına sahip olduğunu beyan ve taahhüt eder. KABİS kaydı veya işletme ruhsatı bulunmayan üyelerin ilanları derhal yayından kaldırılır ve üyelikleri askıya alınır.
2. Fiyat Politikası (Gerçek Günlük Fiyat): 'Kiralık Araç' kategorisindeki ilanlarda girilen fiyat, aracın istisnasız 1 (bir) günlük kiralama bedeli olmak zorundadır. Tüketiciyi yanıltmak ve sıralamada öne geçmek amacıyla; aylık/yıllık kiralama bedelinin gün sayısına bölünmesiyle elde edilen rakamın veya gerçeği yansıtmayan 'temsili' düşük fiyatların günlük fiyat hanesine yazılması yasaktır. Bu kurala uymayan ilanlar reddedilir.
3. Minimum Kiralama Süresi: Üye, eğer aracı 1 günden az kiralamıyorsa (Örn: En az 3 gün veya 1 hafta), bu kısıtlamayı ilan açıklamasında ve (varsa) ilan detay alanlarında net bir şekilde belirtmek zorundadır.
Deniz ve Hava Araçları İlan Kriterleri:
 Aktivite İlan Kriterleri:
	•	Deniz Araçları:  Günübirlik, haftalık veya daha uzun süreli tekne turu hizmeti veren üyeler  Deniz Turizmi Araçları İşletme Belgesini sisteme yüklemesi zorunludur. Belge yüklenmemiş ve Kültür ve Turizm Bakanlığı’ndan doğruluğu yapılamayan ilanlar yayınlanmaz veya yayından kaldırılır. Başkalarına ait belgeleri yükleyerek veya belgede sahtecilik ile verilen ilanlardan tatildesen sorumlu değildir. . Belgelerin geçerliliğini sorgulamak üyenin sorumluluğundadır.

	•	. Yamaç Paraşütü:  Beraberinde  Yolcu uçurmak için girilecek ilanlarda pilot’’Ticari Tandem ‘’ T2 Ticari tandem Sertifikasını sisteme yüklemeyi kabul eder. Genel sağlık muayenesi sağlık raporu ,ferdi kaza ve kolluk sigortası vs belgelerin güncel ,geçerli olduğunu (ilan tarihinde geçerli olan ancak ilan süresi içinde geçerliliğini koruduğunu) tatildesen taahüt etmez. Belgelerin geçerliliğini sorgulamak üyenin sorumluluğundadır.
	•	Sportif Amaçlı Su Faaliyeti: Bu alanda verilecek ilanlar için faaliyeti veren işletmenin
  Deniz Turizmi Aracı İşletme Belgesi, Sportif Turizm Yeterlilik Belgesini sisteme yükler.

 
6. Ödeme Güvenliği ve Dolandırıcılığın Önlenmesi
Ödeme işlemleri yalnızca Tatildesen’in sunduğu güvenli ödeme sistemleri (İyzico vb.) üzerinden yapılmalıdır. Harici yollarla yapılan ödemelerden doğacak sorunlardan Tatildesen sorumlu değildir.İlan sahipleri, kullanıcılarla Tatildesen platformu üzerinden iletişim kurmalıdır. Harici iletişim kanalları üzerinden yapılan anlaşmalardan platform sorumlu tutulamaz.Tatildesen, dolandırıcılık veya kötü niyetli kullanım şüphesi olan ilanları inceleme altına alma ve yayından kaldırma hakkına sahiptir.
7. İlan Denetim ve Onay Süreci
İlanlar, tatildesen ekibi tarafından manuel ve otomatik (yapay zeka) denetim süreçlerinden geçer. Denetim sürecinde ilan içeriği eksik veya hatalı bulunursa ilan reddedilir ya da düzeltme talep edilir. İlanın yayına alınma süresi en fazla ortalama 24 saattir. Ancak gerekli kontrollerin yapılabilmesi için süreç uzayabilir. Tatildesen, kullanıcı deneyimini geliştirmek amacıyla ilanların kategori ve açıklamalarında değişiklik yapma hakkına sahiptir.
8. Yasal ve İdari Düzenlemeler
İlan verenler, yürürlükteki yasalara ve yönetmeliklere uygun hareket etmekle yükümlüdür. Kimlik doğrulama süreçleri eksiksiz tamamlanmalıdır. Kimlik doğrulamayan kullanıcılar ilan veremez. İlanların yasal gereklilikleri karşılamaması halinde Tatildesen, ilgili mercilere bildirimde bulunabilir. İlan içeriklerinde kişisel verilerin korunmasına özen gösterilmelidir. Üçüncü tarafların kişisel verilerinin izinsiz paylaşımı yasaktır.
 
İLAN YAYINLAMA VE SATIŞ SORUMLULUĞU POLİTİKASI
1. Genel AçıklamaTatildesen.com ("Platform"), kullanıcıların ürün ve hizmet ilanlarını yayınlamasına olanak sağlayan bir ilan platformudur. Platformumuz, ilan sahipleri ile alıcıları bir araya getiren bir pazar yeri görevi görür. Tatildesen Tatildesen.com, herhangi bir ürün veya hizmetin satışını doğrudan gerçekleştirmez ve ticari işlemlerde taraf değildir.
2. Tatildesen.com’un Sorumlulukları
Tatildesen, 6563 sayılı Kanun uyarınca yalnızca Aracı Hizmet Sağlayıcı'dır. Tatildesen; Alıcı ve Satıcı arasındaki ürün/hizmet bedeli transferine, kapora ödemesine, ürünün teslimatına, ayıplı mal süreçlerine veya garanti koşullarına taraf değildir, aracılık etmez ve garantör değildir. Kullanıcılar arasındaki para transferi ve ticari anlaşmazlıklar Tatildesen'in sorumluluk alanı dışındadır. Satıcılar tarafından yayınlanan ilan içeriklerinin doğruluğu, ilan edilen ürün veya hizmetlerin kalitesi ve satış sonrası hizmetlerden yalnızca ilan sahibi (satıcı) sorumludur. İlan sahiplerinin sunduğu bilgiler ile EIDS (E-İlan Doğrulama Sistemi) üzerinden doğrulanan bilgiler arasında uyum olması zorunludur. İlan bilgileri ile EIDS sisteminden gelen bilgiler arasında uyumsuzluk tespit edilirse, ilan yayından kaldırılabilir ve satıcıya bildirim yapılır. İlan verene ait kimlik ve yetki bilgilerinin doğruluğundan yalnızca ilan sahibi sorumludur.
E-İlan Doğrulama (EIDS) ve Para Birimi (32 Sayılı Karar): Üye, Gayrimenkul ve Araç ilanlarında Ticaret Bakanlığı mevzuatı gereği E-Devlet üzerinden Kimlik ve Yetki Doğrulaması (EIDS) yapmak zorundadır. Yetki belgesi olmayan veya doğrulanmamış ilanlar yayınlanmaz. Yanıltıcı beyanla girilen veya EIDS kurallarına aykırı ilanlardan doğacak her türlü idari para cezasından (Bakanlık cezaları dahil) doğrudan Üye sorumludur; Tatildesen bu cezaları Üye'ye rücu eder. Ayrıca, 32 Sayılı Karar uyarınca; Türkiye'de yerleşik kişilerin menkul ve gayrimenkul satış/kiralama ilanlarında fiyatların Türk Lirası (TL) olarak girilmesi zorunludur. Döviz cinsinden girilen ilanlar reddedilir.
3. Satıcıların Yükümlülükleri
Satıcılar, ilan verdikleri ürün veya hizmetlerin açıklamalarını eksiksiz ve doğru şekilde sunmakla yükümlüdür. Satıcılar, satışa sundukları ürün veya hizmetin hukuka uygun olduğunu ve gerekli izinleri aldığını taahhüt eder, aksi durumda satıcı bizzat sorumludur. Satış sonrası destek, iade ve garanti gibi süreçlerden tamamen satıcı sorumludur. Satıcı, bu süreçleri ilan detaylarında belirtmek zorundadır.
4. Alıcıların Bilgilendirilmesi
Alıcılar, satın almadan önce satıcı ile iletişime geçerek ürün veya hizmet hakkında detaylı bilgi almalıdır. Platform, satıcılar tarafından sağlanan bilgilerin doğruluğunu garanti etmez ve yanlış beyanlar nedeniyle doğabilecek zararlardan sorumlu tutulamaz. Alıcı, herhangi bir uyuşmazlık durumunda satıcı ile iletişime geçerek çözüm aramakla yükümlüdür. Tatildesen.com bu gibi durumlarda satıcı mağaza görseli, telefon ve isim bilgileri alıcı ile paylaşabilir.
5. Hukuki ve İdari Sorumluluklar
Tatildesen.com, kullanıcılar arasında doğabilecek anlaşmazlıklara müdahale etmez ve hukuki süreçlere taraf olmaz. Platformda yayınlanan ilanların içeriklerinden yalnızca ilan sahipleri (satıcılar) sorumludur.Tatildesen.com, herhangi bir kullanıcının yaptığı alışverişten veya ticari faaliyetten doğabilecek zarar veya kayıplardan sorumlu değildir.
İlan Yayından Kaldırılma ve Askıya Alma Süreci
Tatildesen.com olarak, ilanların doğru, eksiksiz ve güncel bilgiler içermesi gerektiğine önem vermekteyiz. Bu nedenle aşağıdaki durumlarda ilanı askıya alma veya yayından kaldırma hakkımız saklıdır:
Arama Motoru İndeksleri ve Cache Kayıtları İlanın yayından kaldırılması, süresinin dolması veya üyeliğin silinmesi durumunda; Tatildesen sistemlerindeki veri anında pasife alınır. Ancak, Google, Yandex, Bing vb. arama motorlarının önbelleklerinde (cache) veya arama sonuçlarında yer alan verilerin güncellenmesi veya silinmesi Tatildesen'in teknik kontrolü dışındadır. Tatildesen, üçüncü taraf arama motorlarının veri tabanlarında kalan eski kayıtlardan sorumlu tutulamaz. Üye, kişisel veya ticari verilerinin arama motoru indekslerinden silinmesi taleplerini doğrudan ilgili arama motorunun "İçerik Kaldırma" araçları üzerinden ileteceğini kabul eder.
İlanın Gerçeği Yansıtmaması veya Yanıltıcı Bilgi İçermesi:
İlan içeriğinde yanıltıcı, eksik, yanlış veya gerçeği yansıtmayan bilgiler bulunması. İlan görselleri veya videolarının ürün/hizmetle uyumsuz olması veya manipüle edilmiş olması.
Fiyatlandırma Problemleri:
Ürün veya hizmet fiyatının, piyasa değerine göre fahiş şekilde düşük veya yüksek olarak belirlenmesi. ilanın, fiyat spekülasyonu oluşturacak nitelikte düzenlenmesi.
 
Görsel ve Video Uygunsuzlukları:
İlan görselleri veya videolarında yanıltıcı, manipüle edilmiş veya gerçek dışı içeriklerin yer alması. Üçüncü şahıs haklarını ihlal eden görsellerin kullanılması.
Şikayet ve Bildirimler:
İlan hakkında yapılan şikayetler doğrultusunda yapılan incelemelerde uygunsuzluk veya gerçeği yansıtmama tespit edilmesi. Kullanıcı geri bildirimleri ve üçüncü taraf doğrulamaları ile tespit edilen hatalar.
Tatildesen.com, yukarıda belirtilen durumlarda ilanı askıya alma, yayından kaldırma veya düzenleme talep etme hakkına sahiptir. İlan sahibi, düzeltme yapmadığı sürece ilan tekrar yayına alınmayabilir.
Taahhütlü ve Aylık Ödemeli Hizmetlerde İptal ve Ödeme Süreci
Aylık Ödemeli Hizmetlerde Aksama:
Aylık ödeme planına sahip hizmetlerde, kullanıcı iki ay üst üste ödeme yapmadığı takdirde, hizmet askıya alınır.Bu durumda, kalan taahhüt süresinin toplam bedeli tahsil edilir ve kullanıcı, ön ödemeli hizmet modeline geçirilir. Ön ödemeli sistemde, kullanıcı bir sonraki dönem için ödeme yapmadan hizmetten yararlanamaz.
Taahhütlü Hizmetlerde İlan Yayında Kalma Süresi:
Kullanıcının taahhütlü bir aboneliği varsa ve ilanı yayından kaldırmazsa, ilan bir sonraki ayda da yayında kalmaya devam eder. Bu durumda, ilanın yayında kaldığı yeni ay, yenilenen ilan yükleme kredisinden düşülür.Eğer kullanıcının taahhüdü yoksa ve ilan yayınlama paket ücreti ödenmezse, ilan yayından kaldırılır.
Ücretlendirme Politikası
Tüm ücretlendirme ve hizmet bedelleri, Tatildesen.com veya müşteri ilişkileri çağrı merkezinde güncel olarak beyan edilir. Kullanıcı, hizmet satın almadan önce geçerli fiyatlandırma politikasını çağrı merkezinden öğrenmekle yükümlüdür.
 
 
6. Güncellemeler ve Yürürlük
Tatildesen.com, işbu politikayı dilediği zaman güncelleme hakkını saklı tutar. Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır. İşbu politika, Tatildesen.com internet sitesi ve mobil uygulamaları üzerinden erişilebilir ve kullanıcıların bilgisine sunulmuştur.
 Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızın derhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 1. Tatildesen Tarafından Devir: 
Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: 
Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'in onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
 
TOPLULUK KURALLARI & İÇERİK POLİTİKASI
Tatildesen Tatildesen.com, kullanıcıların güvenli, adil ve keyifli bir deneyim yaşamasını sağlamak amacıyla aşağıdaki Topluluk Kuralları & İçerik Politikasını oluşturmuştur. Platformu kullanırken bu kurallara uymanız gerekmektedir.
 
1. KULLANICI DAVRANIŞ KURALLARI
Tatildesen.com kullanıcıları;
Saygılı ve dürüst olmalı, diğer kullanıcılara karşı hakaret, tehdit veya ayrımcılık içeren ifadeler kullanmamalıdır.Dolandırıcılık, sahtekarlık veya yanıltıcı içerikler paylaşmamalıdır.Spam ve gereksiz tekrar eden içerikler eklememelidir.Başkalarının gizlilik haklarına saygı göstermelidir. Kullanıcı bilgilerini izinsiz paylaşmak yasaktır.
Tatildesen markası hakkında sosyal medyada veya diğer platformlarda gerçeğe aykırı karalama kampanyası yürütmek, asılsız "dolandırıcı" iddiasında bulunmak veya marka itibarını hedef alan organize saldırılar düzenlemek yasaktır.
İhlal Durumunda: Kullanıcı hesapları askıya alınabilir, içerikleri kaldırılabilir veya her türlü cezai ve hukuki yasal süreç başlatılabilir.
2. PLATFORMDA YASAKLI İÇERİKLER
Aşağıdaki içerik türleri kesinlikle yasaktır: Müstechen, pornografik, şiddet içerikli veya nefret söylemi içeren içerikler. Irk, din, cinsiyet, siyasi görüş veya engellilik durumuna yönelik ayrımcılık içeren içerikler. Uyuşturucu, alkol veya tütün ürünleriyle ilgili yasa dışı satış teklifleri. Silah, patlayıcı madde veya yasadışı ekipman satışına yönelik içerikler. Yanıltıcı, sahte veya başkalarını dolandırmaya yönelik ilan ve içerikler, terör ve propaganda içerikleri, Telif hakkı ihlali içeren görseller, metinler veya ürünler.
Kullanıcı adı veya mağaza ismi olarak; telefon numarası, web sitesi linki veya başkasına ait marka isimlerinin kullanılması yasaktır.
İhlal Durumunda: İçerikler kaldırılır, kullanıcı hesabı askıya alınabilir ve gerekirse yasal mercilere bildirim yapılır.
Tescilli markaların (Örn: Nike, Adidas, Gucci, Rolex, Apple vb.) taklitleri, logolu kopyaları, replikaları veya "Benzeri" adı altında satılan ürünlerin ilana koyulması kesinlikle yasaktır. "Orijinalinden farksız" yazsanız dahi ilanınız silinir.
Fikri Mülkiyet İhlali ve Uyar-Kaldır Politikası:
1. Replika/Taklit Ürün Yasağı: Üye, Tatildesen.com üzerinde; üçüncü şahısların fikri ve sınai mülkiyet haklarını (Marka, Patent, Tasarım, Telif) ihlal eden; "Replica", "Çakma", "Birebir", "A Kalite", "İhraç Fazlası" veya "Mirror" gibi ifadelerle pazarlanan taklit/sahte ürünleri satamaz. Bu tür ürünlerin satışı Türk Ticaret Kanunu ve Sınai Mülkiyet Kanunu'na göre suçtur.
2. Uyar-Kaldır Prensibi: Tatildesen, 5651 sayılı Kanun kapsamında "Yer Sağlayıcı" sıfatıyla hareket eder. Telif hakkı veya marka sahibi olduğunu belgeleyen kişi/kurumlardan şikayet gelmesi halinde; Tatildesen, ihlale konu ilanı herhangi bir ön incelemeye veya yargı kararına gerek duymaksızın derhal yayından kaldırma, Üye'nin hesabını askıya alma ve Üye'nin kimlik/iletişim bilgilerini yasal süreç başlatılması için hak sahibine veya savcılığa iletme hakkına sahiptir.
3. Tazminat ve Rücu: Üye'nin marka hakkına tecavüz teşkil eden (sahte) ürün satışı nedeniyle, Tatildesen'in üçüncü kişilere tazminat ödemek zorunda kalması veya idari/adli para cezasına çarptırılması durumunda; ödenen tüm bedeller, avukatlık ücretleri ve dosya masraflarıyla birlikte Üye'ye rücu edilir (yansıtılır).
 
3. DOLANDIRICILIK VE GÜVENLİK POLİTİKASI
Tatildesen.com kullanıcıların güvenli bir şekilde alışveriş yapabilmesi için aşağıdaki kuralları uygular:
Yanıltıcı ilanlar, aldatıcı bilgiler ve fiyat manipülasyonları yasaktır. Kullanıcılar, ödeme yapmadan önce ilan detaylarını ve satıcı bilgilerini kontrol etmelidir. Platform dışında yapılan ödemeler veya sahte fatura taleplerine dikkat edilmelidir. Şüpheli bir durum fark edilirse destek ekibine bildirilmelidir.
 
Güvenli Alışveriş İçin Öneriler:
Ödemelerinizi yalnızca platform içerisindeki güvenli sistemler üzerinden yapın. Bilinmeyen hesaplara veya üçüncü şahıslara ödeme yapmayın. Şüpheli ilanları "Şikayet Et" butonunu kullanarak veya çağrı merkezine bildirin.
4. HUKUKİ VE YASAL UYGUNLUK
Tatildesen.com platformunu kullanan tüm kullanıcılar;
Türk Ceza Kanunu, Tüketicinin Korunması Hakkında Kanun, Elektronik Ticaret Kanunu ve diğer ilgili tüm yasal mevzuata uymakla yükümlüdür. İçeriklerinde yasal olmayan ifadeler veya faaliyetler barındıramaz. Vergi ve yasal yükümlülüklerini yerine getirmelidir.
İhlal Durumunda: Kullanıcı hesapları yasalar çerçevesinde incelenebilir ve resmi mercilere rapor edilebilir.
5. TELİF HAKKI VE FİKRİ MÜLKİYET POLİTİKASI
Tatildesen.com'da başkalarına ait içerikleri izinsiz paylaşmak yasaktır.
Başkasına ait görseller, videolar, metinler veya marka logoları izinsiz olarak kullanılamaz. Telif hakkı ihlali içeren ilanlar veya içerikler tespit edildiğinde yayından kaldırılır. Hak sahibi, içerik ihlali nedeniyle Tatildesen.com’a başvurabilir.
İhlal Durumunda: İçerikler kaldırılabilir ve tekrar eden ihlallerde hesap kapatılabilir.
6. HESAP GÜVENLİĞİ VE PAYLAŞIM POLİTİKASI
Kullanıcılar, hesap şifrelerini kimseyle paylaşmamalıdır. Hesap güvenliği için iki faktörlü doğrulama (2FA) kullanılması önerilir. Hesabınızı üçüncü kişilere devretmek veya satmak yasaktır.Tatildesen.com tarafından gönderilen resmi e-postalar dışındaki şüpheli e-postalara yanıt vermeyin.
İhlal Durumunda: Hesap güvenliği ihlal edilen kullanıcıların hesapları geçici olarak askıya alınabilir veya kalıcı olarak kapatılabilir. Kural ihlali yapan kullanıcının sadece mevcut hesabı değil, tespit edilen diğer tüm yan hesapları da kapatılır.
Not: Tatildesen.com, topluluk kurallarını ve içerik politikasını değiştirme hakkını saklı tutar. Kullanıcılar, en güncel politika kurallarına uymakla yükümlüdür.
 
 
8.⁠ ⁠Sorumluluk Reddi ve Aracı Hizmet Sağlayıcı Beyanı: Tatildesen, 6563 sayılı Kanun uyarınca yalnızca Aracı Hizmet Sağlayıcı'dır. Tatildesen; Alıcı ve Satıcı arasındaki ürün/hizmet bedeli transferine, kapora ödemesine, ürünün teslimatına, ayıplı mal süreçlerine veya garanti koşullarına taraf değildir, aracılık etmez ve garantör değildir. Kullanıcılar arasındaki para transferi ve ticari anlaşmazlıklar Tatildesen'ın sorumluluk alanı dışındadır.
Portalda yayınlanan ilanlardaki ürünlerin kalitesi, orijinalliği (sahteliği), garantisi, ayıplı olup olmaması, ilanın içeriğinin doğruluğu veya ürünün yasalara uygunluğu Tatildesen.com'un taahhüdü ve sorumluluğu altında değildir.
 
Alım-satım, teslimat, ödeme, iptal, iade, garanti ve satış sonrası hizmetlere ilişkin tüm süreçler ve yasal yükümlülükler doğrudan Alıcı ile Satıcı (Üye) arasında yürütülür. Tatildesen.com, bu süreçlere hiçbir şekilde müdahil olmaz ve bu süreçlerden kaynaklanan uyuşmazlıklarda taraf değildir.
 
Alıcı, bir ürünü satın almadan önce ilan detaylarını incelemekle, ürünü ve Satıcı (Üye) hakkındaki güvenilirliği araştırmakla bizzat yükümlüdür. Alıcı ile Satıcı arasındaki güven ilişkisi ve alım-satım kararı tamamen Alıcı'nın kendi inisiyatifi ve sorumluluğundadır.
 
Tatildesen.com, kullanıcılar (alıcı ve satıcı) arasında platform üzerinden veya platform dışında doğabilecek hiçbir hukuki, cezai veya mali anlaşmazlıktan sorumlu tutulamaz.
 
 
 
 
KULLANIM KOŞULLARI
 
1. KULLANIM KOŞULLARI
Tatildesen Bilişim A.Ş. Tatildesen.com internet sitesini veya mobil uygulamalarını kullanmadan önce lütfen aşağıda belirtilen koşulları dikkatlice okuyunuz. Tatildesen.com internet sitesini ziyaret ederek, mobil uygulamalarını kullanarak ve/veya üye olarak, işbu Kullanım Koşullarını okuduğunuzu, içeriğini anladığınızı ve tüm koşulları kabul ettiğinizi beyan edersiniz. Tatildesen.com, kullanım koşullarını ve sunulan hizmetleri önceden haber vermeksizin değiştirme hakkına sahiptir, ancak kullanıcıların hukuki durumunu etkileyen değişiklilikleruygulama veya mail ile bilgilendirilecektir. Kullanıcılar, güncellenmiş kullanım koşullarına uymayı kabul etmiş sayılır.
 
2. TANIMLAR
Portal: Tatildesen.com’un internet sitesi ve mobil uygulamaları.Kullanıcı: Portala erişen ve hizmetlerden yararlanan her gerçek veya tüzel kişi.Hesap Sahibi: Portalda hesabı bulunan ve hizmetleri kullanan kişi.İçerik: Portalda yer alan her türlü bilgi, yazı, görsel, video ve ses içeriği.Tatildesen Veritabanı: Kullanıcılar tarafından yüklenen içeriklerin saklandığı ve korunduğu sistem.
 
3. TATİLDESEN  HİZMETLERİ
Tatildesen.com aşağıdaki hizmetleri sunar:
Kullanıcılara ilan yayınlama imkanı. Ürün ve hizmetlerin tanıtımını sağlama. Kullanıcılar arasında güvenli bir platform oluşturma. Farklı kategorilerde ilan listeleme hizmeti sunma. Kullanıcılara alıcı ve satıcı arasında mesajlaşma imkanı sunma.
Tatildesen, hizmetleri değiştirme, geliştirme, ekleme veya kaldırma hakkına sahiptir. Kullanıcılar, bu hizmet değişikliklerini kabul etmiş sayılır.
Tatildesen.com üzerinde listelenen ustalar, nakliyeciler veya hizmet sağlayıcılar, platformun çalışanı veya temsilcisi değildir. Tatildesen, bu kişilerin mesleki yeterliliğini, güvenilirliğini veya iş kalitesini garanti etmez. Hizmet alımı sırasında oluşabilecek zararlardan, hırsızlık veya hasar durumlarından Tatildesen sorumlu tutulamaz. Kullanıcı, hizmet verenle anlaşmadan önce gerekli araştırmayı bizzat kendisi yapmalıdır.
Otomatik İçerik Filtreleme ve Dolandırıcılık Önleme: Tatildesen; platform üzerinden gerçekleşebilecek "Kapora Dolandırıcılığı", kara para aklama ve yasadışı ticareti engellemek amacıyla, site içi mesajlaşma trafiğini yapay zeka ve otomatik filtreleme sistemleri ile 7/24 tarama hakkına sahiptir. Sistem;
1. Mesaj içeriğinde IBAN numarası, ödeme talep eden ifadeler ("Kapora at", "Hesaba geç"),
2. Genel ahlaka aykırı küfür, hakaret, tehdit veya taciz içeren metinler,
3. Yasadışı ürün/hizmet pazarlaması tespit ettiğinde; mesajı alıcıya iletmeme, sansürleme (maskeleme) veya Üye'nin hesabını geçici/kalıcı olarak askıya alma yetkisine sahiptir. Üye, mesajlaşma gizliliğinin; kamu güvenliği, suçun önlenmesi ve platformun temiz kalması amacıyla bu teknik denetimlere tabi olduğunu peşinen kabul eder. Tatildesen, engellenen bir mesaj nedeniyle doğacak ticari kayıplardan sorumlu tutulamaz.
 
 
4. KULLANICI YÜKÜMLÜLÜKLERİ
Kullanıcılar, yalnızca hukuka uygun işlemler yapmakla yükümlüdür. Dolandırıcılık, sahte ilan, yanıltıcı bilgi ve aldatıcı içerikler yasaktır. Kullanıcılar, ilan ve mesajlarında genel ahlaka, kamu düzenine ve ticari etik kurallarına uygun hareket etmelidir. Kullanıcı, portal üzerinde gerçekleştirdiği işlemlerden hukuki ve cezai yönden bizzat sorumludur. Kullanıcı, hesabına erişim yetkisi verdiği kişilerin veya hesabının güvenliğini sağlamayarak yetkisiz erişime sebep olduğu durumların sonuçlarından doğrudan sorumludur.
5. İÇERİK YÖNETİMİ VE DENETİMİ
Tatildesen, platformda paylaşılan içeriklerin doğruluğunu garanti etmez. Kullanıcılar, yükledikleri içeriklerin yasalara ve portal kurallarına uygun olduğunu taahhüt eder. Sahte ilanlar, yanlış bilgi içeren veya yanıltıcı içerikler tespit edilirse ilan kaldırılabilir ve kullanıcı hesabı askıya alınabilir. Tatildesen, kullanıcıların sunduğu içeriği düzenleme, inceleme veya kaldırma hakkına sahiptir.
6. FİKRİ MÜLKİYET HAKLARI
Portalda yer alan tüm içerik, veri, yazılım, tasarım ve görseller Tatildesen’e aittir. Kullanıcılar, Tatildesen içeriğini kopyalayamaz, işleyemez, dağıtamaz veya üçüncü kişilerle paylaşamaz. Aksi durumda hukuki ve cezai sorumluluğu kullanıcıya aittir.
İÇERİK LİSANSI: Kullanıcı, Platforma yüklediği her türlü içeriğin (açıklama, ilan, fotoğraf, video); Tatildesen'in ticari faaliyetleri, tanıtımı ve reklamları kapsamında, yurtiçi ve yurtdışında, herhangi bir telif ücreti ödenmeksizin süresiz olarak kullanılabileceğini kabul eder. Kullanıcı, sisteme içerik yüklediği anda Tatildesen'e bu konuda geniş kapsamlı bir kullanım lisansı vermiş sayılır.
VERİ KAZIMA VE TERSİNE MÜHENDİSLİK YASAĞI: Kullanıcıların veya ziyaretçilerin; Platform üzerindeki herhangi bir veriyi (ilan, fiyat, görsel, kullanıcı bilgisi vb.); bot, örümcek (spider), crawler, screenscraping yazılımları, veri madenciliği veya benzeri otomatik sistemler kullanarak çekmesi, kopyalaması, işlemesi ve başka bir mecrada yayınlaması kesinlikle yasaktır. Platform'un kaynak kodlarına, arayüzüne veya veritabanına yönelik tersine mühendislik (reverse engineering) yapmak, API açıklarını aramak veya sistemin işleyişini bozacak yük bindirmek suçtur. Tatildesen, bu tür faaliyetlerde bulunan IP adreslerini engelleme ve Cumhuriyet Başsavcılığı'na suç duyurusunda bulunma hakkını saklı tutar.
Platformun sunduğu araçlarla (AI, filtre vb.) değiştirilen veya üretilen içeriklerin mülkiyeti Tatildesen'a aittir, kaynak gösterilerek dahi başka ticari mecralarda kullanılamaz.
Veri Tabanı Mülkiyeti ve Veri Madenciliği Yasağı: Tatildesen Platformu'nda yer alan; ilan metinleri, fiyat verileri, kullanıcı yorumları, istatistiki bilgiler, raporlar, analiz grafikleri ve veri tabanı yapısı üzerindeki tüm mali haklar, mülkiyet hakları ve "Sui Generis Veri Tabanı Hakkı" münhasıran Tatildesen'e aittir.
Kullanıcılar veya üçüncü şahıslar (rakip firmalar, veri toplayıcılar);
1. Tatildesen'in yazılı izni olmaksızın site içeriğini kopyalayamaz, başka bir mecrada yayınlayamaz.
2. Site üzerinde "Screen Scraping" (Ekran Kazıma), "Data Mining" (Veri Madenciliği), bot, örümcek (spider) veya otomatik yazılımlar kullanarak veri çekemez.
3. İlan açıklamalarını ve fiyat bilgilerini toplayıp, Tatildesen ile rekabet edecek başka bir veri tabanı oluşturamaz. Bu yasağın ihlali halinde Tatildesen; 5846 sayılı FSEK ve Türk Ticaret Kanunu hükümleri uyarınca "Haksız Rekabet" davası açma ve maddi/manevi tazminat talep etme hakkını saklı tutar.
Genişletilmiş Veri Kullanım Hakkı: Üye, sisteme girdiği ilan metinlerinin, teknik özelliklerin ve fotoğrafların; Tatildesen tarafından işlenmesine, anonimleştirilerek pazar analizi raporlarına dönüştürülmesine, fiyat endekslerinde kullanılmasına ve Tatildesen'in iş ortaklarıyla (değerleme firmaları vb.) ticari amaçla paylaşılmasına gayrikabili rücu (geri alınamaz) onay verir. Üye, Tatildesen veritabanında oluşan bu istatistiki veriler üzerinde (kendi ilanı kaynaklı olsa dahi) herhangi bir telif veya hak iddiasında bulunamaz.
 
7. MÜCBİR SEBEP
Aşağıdaki durumlardan doğan hizmet aksaklıklarında Tatildesen sorumlu tutulamaz:
Doğal afetler (deprem, sel, yangın vb.).Siber saldırılar, altyapı sorunları veya hizmet kesintileri. Üçüncü taraf hizmet sağlayıcı kaynaklı arızalar. Yasal düzenlemeler nedeniyle hizmetin kısıtlanması.
8. UYGULANACAK HUKUK VE YETKİ
Kullanım Koşulları, Türkiye Cumhuriyeti yasalarına tabidir. Tatildesen ile kullanıcılar arasındaki ihtilaflarda Ankara Mahkemeleri ve İcra Daireleri yetkilidir.
FİKRİ MÜLKİYET VE VERİ GÜVENLİĞİ Kurumsal Üye, Platform üzerindeki verilerin (ilan, fiyat, istatistik vb.) Tatildesen'in fikri mülkiyetinde olduğunu kabul eder. Üye, rekabet analizi veya başka amaçlarla Platform'daki verileri manuel veya otomatik yazılımlar (bot, scraper vb.) aracılığıyla çekemez, kopyalayamaz. Aksi takdirde Tatildesen, üyeliği derhal iptal etme ve uğradığı ticari zararı tazmin etme hakkına sahiptir.
Tatildesen.com Veritabanı; içeriğin seçilmesi, düzenlenmesi ve tertibi konusunda Tatildesen'ın yaptığı nitelikli yatırım ve organizasyon sonucunda oluşturulmuş olup; 5846 Sayılı Fikir ve Sanat Eserleri Kanunu ve ilgili mevzuat uyarınca 'Veritabanı Yapımcısı' sıfatıyla münhasıran Tatildesen'ın mülkiyetindedir. Bu veritabanının bütününe veya ticari açıdan önemli bir kısmına yönelik izinsiz erişim, kopyalama, başka bir veritabanına aktarma (extraction) veya tekrar kullanım (re-utilization) işlemleri; Tatildesen'ın 'Sui Generis' (Nev'i Şahsına Münhasır) haklarının ihlali sayılır. İhlal edenler hakkında hapis ve adli para cezası dahil olmak üzere ağır cezai ve hukuki yaptırımlar uygulanır.
Tatildesen.com veritabanı üzerindeki tüm mali, manevi ve ticari haklar Tatildesen e aittir. Veritabanıiçeriğinin (ilanlar, fiyatlar, kullanıcı verileri) izinsiz olarak kısmen veya tamamen kopyalanması, başka bir sunucuya aktarılması veya işlenmesi; 5846 sayılı FSEK Ek Madde 4 uyarınca suçtur. Tatildesen, veritabanı yapımcısı olarak kanundan doğan tüm dava ve şikayet haklarını saklı tutar.
TACİR SIFATI VE YARGI YOLU Kurumsal Üye, işbu sözleşmeyi mesleki ve ticari faaliyetleri kapsamında akdettiğini, 6102 sayılı Türk Ticaret Kanunu uyarınca "Tacir" veya "Esnaf" sıfatına haiz olduğunu ve bu nedenle 6502 sayılı Tüketicinin Korunması Hakkında Kanun hükümlerine tabi olmadığını kabul eder. Üye, Sözleşme'den doğacak uyuşmazlıklarda Tüketici Hakem Heyetleri'nin veya Tüketici Mahkemeleri'nin görevli olmadığını; uyuşmazlıkların çözümünde Ankara - mevcut yetki maddesindeki şehir Asliye Ticaret Mahkemeleri'nin münhasır yetkili olduğunu beyan ve taahhüt eder.
9. YÜRÜRLÜK VE KABUL
Bu Kullanım Koşulları, Tatildesen.com’da yayınlandığı tarihten itibaren geçerli olup kullanıcılar tarafından kabul edilmiş sayılır.
Tatildesen, Kullanım Koşulları'nı önceden haber vermeksizin değiştirme hakkını saklı tutar. Değişiklikler sitede yayınlandığı anda yürürlüğe girer ve siteyi kullanmaya devam eden herkes bu değişiklikleri kabul etmiş sayılır.
Kullanıcılar, Tatildesen platformunu kullanarak tüm koşulları kabul etmiş sayılır.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'ın onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
HİZMET BEDELİ İADE POLİTİKASI
1. Tatildesen Bilişim A.Ş. Tatildesen.com ("Platform"), satıcıların ilanlarını yayınlamasına olanak sağlayan bir ilan platformudur. Satıcıların ilanlarını yayınlanabilmesi için belirli hizmet bedelleri ve komisyon ücretleri alınmaktadır. İşbu politika, hizmet bedellerinin ve komisyon iade süreçlerinin yanı sıra abonelik iptalleri ve iade politikalarını da kapsamaktadır.
2. Hizmet Bedeli ve Komisyon Ücretleri
Satıcılar, ilanlarını yayınlamak veya platform içi ek hizmetlerden yararlanmak için belirlenen hizmet bedellerini ödemekle yükümlüdür.
3. Hizmet Bedeli ve Komisyon İade Koşulları
İlan Yayınlama Ücreti: Yayınlanan bir ilan için alınan ücret, ilan yayında olduğu sürece iade edilmez.
Hatalı İşlem veya Çift Tahsilat: Teknik bir hata nedeniyle fazla tahsil edilen komisyon veya hizmet bedelleri, inceleme sonrasında satıcıya iade edilir.
Özel Kampanya ve İndirimler: Kampanya kapsamında belirlenen hizmet bedelleri ve komisyonlar, iade süreçlerinde ana paket ücreti üzerinden değerlendirilir.
4. Abonelik İptali ve İade Politikası
Abonelik İptali: Kurumsal üyeler, aboneliklerini diledikleri zaman iptal edebilir. Ancak, taahhütlü aboneliklerde erken iptal yapılması halinde, yapılan indirim veya kalan indirim hesaplanarak kullanıcı lehine olan bedel tahsil edilir.
   İptal ve İade Süreci:
İade ve iptal işlemleri, kullanıcının talebi üzerine platform üzerinden başlatılır.İade koşullarına uygun görülen tutarlar, ilgili ödeme aracısının politikalarına görebelirlenir.İade edilecek tutar, ödeme aracısı (sanal POS firması) tarafına bildirilir ve kullanıcının hesabına aktarılır.İade süresi, ödeme aracısının işlem sürecine bağlı olup, bu süreye platform müdahale edemez.Kart güvenliği ve iade süreci tamamen ödeme a. racısının hüküm ve koşullarına tabidir. Muhatap, doğrudan ödeme aracısıdır.
5. İade Koşulları
Tatildesen tarafından sunulan İlan Yayınlama, Doping (Boost), Vitrin ve Mağaza abonelik hizmetleri; elektronik ortamda anında ifa edilen hizmet ve gayrimaddi mal niteliğindedir. Bu nedenle, 6502 sayılı Kanun ve Mesafeli Sözleşmeler Yönetmeliği Madde 15/ğ uyarınca Kullanıcı'nın bu hizmetlerde Cayma Hakkı bulunmamaktadır. Hizmet satın alındığı veya aktif edildiği an ifa edilmiş sayılır ve hiçbir koşulda ücret iadesi yapılmaz.
İhlal Nedeniyle İadesizlik : Kullanıcı'nın üyeliği, mağazası veya ilanı; Mevzuat'a, İlan Verme Kuralları'na veya işbu Sözleşme'ye aykırılık teşkil etmesi (spam, dolandırıcılık, yanıltıcı beyan, hakaret, tehdit vb.) sebebiyle Tatildesen tarafından askıya alınırsa veya iptal edilirse; Kullanıcı'nın o ilan, üyelik dönemi veya paket için ödediği ücretler (İlan Ücreti, Doping/Boost, Mağaza Bedeli) iade edilmez ve Tatildesen'a irat kaydedilir. Kullanıcı, kendi kusuruyla sözleşmenin feshine sebep olduğu bu durumlarda herhangi bir tazminat veya iade talep hakkı bulunmadığını kabul eder.
 
6. Güncellemeler ve Yürürlük
Tatildesen.com, hizmet bedeli, komisyon ve iade politikasını dilediği zaman güncelleme hakkını saklı tutar. Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır. İşbu politika, Tatildesen.com internet sitesi ve mobil uygulamaları üzerinden erişilebilir ve kullanıcıların bilgisine sunulmuştur.
 
 Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'in onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
 
VERİ SAKLAMA & İMHA POLİTİKASI
1. Tatildesen Bilişim A.Ş. Tatildesen.com ("Platform"), kullanıcıların kişisel verilerini Kişisel Verilerin Korunması Kanunu (KVKK), Genel Veri Koruma Tüzüğü (GDPR) ve diğer ilgili mevzuatlara uygun olarak saklamakta ve gerektiğinde imha etmektedir. Bu politika, verilerin ne kadar süreyle saklanacağını, hangi yöntemlerle imha edileceğini ve veri güvenliğinin nasıl sağlanacağını düzenler.
 
2. Veri Saklama Süreleri Kullanıcı verileri, işleme amaçları doğrultusunda belirli süreler boyunca saklanır:
Üyelik Bilgileri: Hesap silindiğinde, yasal yükümlülüklere uygun olarak 5 yıl saklanır ve ardından imha edilebilir. Ödeme ve Finansal Veriler: Vergi mevzuatı gereği, işlem tarihinden itibaren 10 yıl süreyle saklanır. Müşteri Destek Kayıtları: Kullanıcı taleplerini değerlendirmek amacıyla en az 2 yıl süreyle saklanır. Çerezler ve Analitik Veriler: Kullanıcının tercih ettiği çerez politikalarına bağlı olarak 1 yıl süreylesaklanır.Hukuki ve Şikayet Kayıtları: Mevcut hukuki yükümlülükler çerçevesinde 10 yıl boyunca saklanabilir.
 
3. Veri Saklama Yöntemleri Tatildesen.com, verileri güvenli sunucularda ve şifrelenmiş formatlarda saklar. Kullanıcı verilerine yetkisiz erişimi önlemek için aşağıdaki güvenlik önlemleri uygulanmaktadır:
Veri Şifreleme: Kullanıcı verileri şifreleme protokolleri ile korunur.Yetkilendirme Politikaları: Yalnızca yetkili personel, belirlenen güvenlik seviyelerine göre verilere erişebilir.Sistem Yedekleme: Veri kaybını önlemek için günlük, haftalık ve aylık yedekleme prosedürleri uygulanır.Sızma Testleri: Düzenli olarak güvenlik denetimleri ve sızma testleri gerçekleştirilir.
 
4. Veri İmha Yöntemleri Tatildesen.com, yasal saklama süresi dolan veya işleme amacı sona eren kişisel verileri silme, anonim hale getirme veya yok etme yöntemleriyle imha eder.
Fiziksel Yok Etme: Kağıt ortamında saklanan belgeler güvenli şekilde imha edilir.Dijital Veri Silme: Sistemlerden silme komutları ile kalıcı olarak veri kaldırılır.Anonimleştirme: Kişisel verilerin kimliği belirlenemeyecek hale getirilerek, analiz ve raporlama amaçlı kullanılmasına devam edilebilir.
5. Kullanıcı Hakları ve Talepler Kullanıcılar, KVKK ve GDPR kapsamında aşağıdaki haklara sahiptir:
Saklanan kişisel verilerine erişim talep edebilir.Verilerinin düzeltilmesini veya güncellenmesini isteyebilir.Belirlişartlar altında verilerinin silinmesini talep edebilir.İşlenen verilerinin hangi amaçlarla kullanıldığını öğrenebilir.
6. Veri İhlali Bildirimi Tatildesen.com, herhangi bir veri ihlali durumunda, ilgili kullanıcılara ve yetkili kurumlara en geç 72 saat içinde bildirimde bulunacaktır. Veri ihlalleriyle ilgili tüm kayıtlar düzenli olarak tutulmaktadır.
7. Ödeme Entegrasyonu 
Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır.Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder.Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
8. Güncellemeler ve Yürürlük
Tatildesen.com, işbu Veri Saklama & İmha Politikasını güncelleme hakkını saklı tutar.Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır.
Bu politika, Tatildesen.com'da işlem yapan tüm kullanıcılar için bağlayıcıdır ve platformu kullanmaya devam eden kullanıcılar, belirtilen veri saklama ve imha süreçlerini kabul etmiş sayılırlar.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. 
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'ın önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'ın onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
 

`;

export default function CorporateMembershipAndStoreAgreementPage() {
  return (
    <article className="mx-auto w-full max-w-[820px] space-y-8 px-4 pb-24 pt-10 md:px-0 md:pt-14">
      <header className="space-y-3 text-center">
        <span className="inline-flex items-center justify-center rounded-full bg-primary/10 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-primary">
          Sözleşme
        </span>
        <h1 className="text-3xl font-semibold tracking-tight text-foreground md:text-4xl">
          Kurumsal Üyelik ve Mağaza Sözleşmesi
        </h1>
      </header>

      <section className="rounded-3xl border border-border bg-white/90 p-6 shadow-sm shadow-black/5">
        <div className="whitespace-pre-wrap break-words text-sm leading-relaxed text-muted-foreground">
          {agreementText}
        </div>
      </section>
    </article>
  );
}
