export interface User {
  id: string;
  name: string;
  email: string;
  role: "admin" | "owner" | "traveler";
  status: "active" | "suspended" | "pending";
  avatar?: string;
  phone?: string;
  createdAt: Date;
  lastLoginAt?: Date;
  placeCount?: number;
  subscriptionStatus?: "active" | "expired" | "cancelled" | null;
}

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ahmet Yılmaz",
    email: "ahmet@example.com",
    role: "owner",
    status: "active",
    phone: "+90 532 123 4567",
    createdAt: new Date("2024-01-15"),
    lastLoginAt: new Date("2024-11-14T10:30:00"),
    placeCount: 3,
    subscriptionStatus: "active",
    avatar: "/avatars/user1.jpg",
  },
  {
    id: "2",
    name: "Ayşe Demir",
    email: "ayse@example.com",
    role: "owner",
    status: "active",
    phone: "+90 212 987 6543",
    createdAt: new Date("2024-02-20"),
    lastLoginAt: new Date("2024-11-14T09:15:00"),
    placeCount: 2,
    subscriptionStatus: "active",
    avatar: "/avatars/user2.jpg",
  },
  {
    id: "3",
    name: "Mehmet Kaya",
    email: "mehmet@example.com",
    role: "traveler",
    status: "active",
    phone: "+90 533 456 7890",
    createdAt: new Date("2024-03-10"),
    lastLoginAt: new Date("2024-11-13T18:45:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
    avatar: "/avatars/user3.jpg",
  },
  {
    id: "4",
    name: "Zeynep Çelik",
    email: "zeynep@example.com",
    role: "owner",
    status: "active",
    phone: "+90 216 234 5678",
    createdAt: new Date("2024-04-05"),
    lastLoginAt: new Date("2024-11-14T14:20:00"),
    placeCount: 1,
    subscriptionStatus: "active",
    avatar: "/avatars/user4.jpg",
  },
  {
    id: "5",
    name: "Can Öztürk",
    email: "can@example.com",
    role: "traveler",
    status: "active",
    phone: "+90 535 678 9012",
    createdAt: new Date("2024-05-18"),
    lastLoginAt: new Date("2024-11-14T16:10:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
  },
  {
    id: "6",
    name: "Admin User",
    email: "admin@tatildesen.com",
    role: "admin",
    status: "active",
    phone: "+90 212 555 0123",
    createdAt: new Date("2024-01-01"),
    lastLoginAt: new Date("2024-11-14T11:00:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
    avatar: "/avatars/admin.jpg",
  },
  {
    id: "7",
    name: "Fatma Yıldız",
    email: "fatma@example.com",
    role: "owner",
    status: "suspended",
    phone: "+90 542 111 2222",
    createdAt: new Date("2024-06-22"),
    lastLoginAt: new Date("2024-10-28T15:30:00"),
    placeCount: 4,
    subscriptionStatus: "cancelled",
    avatar: "/avatars/user5.jpg",
  },
  {
    id: "8",
    name: "Ali Vural",
    email: "ali@example.com",
    role: "owner",
    status: "pending",
    phone: "+90 312 333 4444",
    createdAt: new Date("2024-07-30"),
    lastLoginAt: undefined,
    placeCount: 0,
    subscriptionStatus: undefined,
  },
  {
    id: "9",
    name: "Elif Aksoy",
    email: "elif@example.com",
    role: "traveler",
    status: "active",
    phone: "+90 505 777 8888",
    createdAt: new Date("2024-08-12"),
    lastLoginAt: new Date("2024-11-14T13:25:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
  },
  {
    id: "10",
    name: "Murat Demir",
    email: "murat@example.com",
    role: "owner",
    status: "active",
    phone: "+90 262 999 0000",
    createdAt: new Date("2024-09-05"),
    lastLoginAt: new Date("2024-11-14T17:40:00"),
    placeCount: 2,
    subscriptionStatus: "active",
    avatar: "/avatars/user6.jpg",
  },
  {
    id: "11",
    name: "Selin Korkmaz",
    email: "selin@example.com",
    role: "traveler",
    status: "active",
    phone: "+90 531 888 9999",
    createdAt: new Date("2024-09-20"),
    lastLoginAt: new Date("2024-11-13T20:15:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
  },
  {
    id: "12",
    name: "Hüseyin Gül",
    email: "huseyin@example.com",
    role: "traveler",
    status: "active",
    phone: "+90 507 666 7777",
    createdAt: new Date("2024-10-10"),
    lastLoginAt: new Date("2024-11-14T12:55:00"),
    placeCount: 0,
    subscriptionStatus: undefined,
  },
];

export const roleOptions = [
  { value: "all", label: "Tüm Rollar" },
  { value: "admin", label: "Admin" },
  { value: "owner", label: "Mekan Sahibi" },
  { value: "traveler", label: "Seyahatçi" },
];

export const statusOptions = [
  { value: "all", label: "Tüm Durumlar" },
  { value: "active", label: "Aktif" },
  { value: "suspended", label: "Askıya Alınmış" },
  { value: "pending", label: "Beklemede" },
];
