import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bireysel Üyelik ve İlan Yayınlama Sözleşmesi | TatilDesen",
  description: "Bireysel üyelik ve ilan yayınlama sözleşmesi metni.",
};

const agreementText = `TATİLDESEN.COM  BİREYSEL ÜYELİK VE İLAN YAYINLAMA SÖZLEŞMESİ
1. Taraflar
İşbu sözleşme (bundan böyle “Sözleşme” olarak anılacaktır), aşağıda bilgileri verilen taraflar arasında, KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN  (bundan böyle “Tatildesen” olarak anılacaktır) ile Tatildesen.com platformunda bireysel üyelik oluşturan ve hizmetlerden yararlanan gerçek kişi (bundan böyle “Üye” olarak anılacaktır) arasında elektronik ortamda akdedilmiştir.
2. Tanımlar
Portal: Tatildesen.com’un internet sitesi ve mobil uygulamalar aracılığıyla sunduğu hizmetler.
Üyelik: Üyenin Portal’da bireysel hesap oluşturma, ilan verme ve diğer hizmetlerden faydalanma hakkıdır.
İlan: Üyenin, Platform’da yayınlanmak üzere hazırladığı, hizmet veya ürün tanıtımını içeren metin, resim, video vb. içeriklerin tümü.
Yapay Zeka Kontrolü: İlan içeriklerinin ilk aşamada otomatik sistemler tarafından denetlenerek uygunsuz, yanıltıcı veya hukuka aykırı unsurların tespit edilmesi sürecidir.
Son Kontrol: Yapay zeka denetiminden geçen ilanların, Tatildesen’e bağlı yetkili ekibin son incelemesidir.
İlan Onay Süresi: İlanın, yapay zeka kontrolü ve son kontrol aşamasından geçtikten sonra yayına alınmasına kadar geçen süre (24 saat).
3. İlan Verme Kuralları
3.1. Genel İlan Kuralları
İlanlar doğru, eksiksiz ve güncel bilgiler içermelidir. Yanıltıcı, eksik veya hatalı bilgi içeren ilanlar yayından kaldırılabilir. Aynı ürün veya hizmet için birden fazla ilan açmak yasaktır. Aynı içerikte yinelenen ilanlar otomatik olarak kaldırılacaktır., İlanlara en az 3 adet görsel eklemek zorunludur. Fiyat bilgisi doğru girilmek zorundadır eğer yıl içinde tarihlere göre fiyat farklılık gösteriyorsa her tarih için fiyat ve güncel doluluk durumu verilecek hizmetin konumu, faaliyetin yada konaklamanın başlangıç bitiş saatleri doğru ve eksiksiz olarak girilmeli ve fiyat değişimlerinde güncellenmelidir. Eksik veya gerçeğe aykırı fiyat beyanları içeren ilanlar yayınlanmaz. ilan yayınlandıktan sonra fiyat konum veya takvim doluluk durumunun doğru olmadığı veya girilen bilgiler ile gerçekte sunulan hizmetin uyuşmaması durumunda  ilan kaldırılır ve üyelik ücretleri iade edilmez. İlan bilgilerinde girilen hatalı bilgiler tamamen satıcının kendisine aittir. İlan bilgileri EIDS sistemi ile doğru olmalıdır. Yanıltıcı bilgi girilmesi durumunda firmanın tazminat ve suç duyurusu hakkı saklıdır.
Tatildesen, ilan yayınlama aşamasında e-Devlet entegrasyonu ile EIDS (Elektronik İlan Doğrulama Sistemi) üzerinden kimlik ve yetki doğrulaması yapar. Üye, doğrulama yapmadan ilan veremez. Doğrulama yapılmayan veya manipüle edilen ilanlar nedeniyle kesilecek idari cezalar Üye'ye yansıtılır. Ayrıca Üye, 32 Sayılı Karar gereği ilan fiyatlarını sadece Türk Lirası (TL) cinsinden belirlemek zorundadır. Dövizle ilan girişi yasaktır.
Üye, 'Hizmetler' kategorisinde sunduğu işlerde (boya, tadilat, özel ders vb.) münhasıran kendisi sorumludur. Tatildesen, sadece bir "Yer Sağlayıcı" olarak tarafları bir araya getirir; yapılan işin sonucuna, kalitesine veya ödemesine kefil değildir. Üye, hizmet verdiği kişiyle yaşayacağı anlaşmazlıklarda Tatildesen'ı taraf gösteremez.
3.2. Yasaklı ve Kısıtlı İlanlar
Yanıltıcı, aldatıcı, sahte veya gerçek dışı bilgiler içeren ilanlar yasaktır.Her türlü müstehcen, pornografik içerik veya yasa dışı unsurlar içeren ilanlar yasaktır. Terör propagandası, kamu düzenini bozan içerikler, devlet aleyhine ifadeler içeren ilanlar yasaktır. Üçüncü şahısların marka, patent veya telif hakkını ihlal eden içerikler yasaktır. Sahte, çalıntı veya yasalara aykırı ürünlerin satışına yönelik ilanlar yayınlanamaz. Yanlış kategoriye yerleştirilmiş ilanlar düzeltme talebiyle reddedilebilir veya kaldırılabilir.
Evcil Hayvan Satış Yasağı ve Sahiplendirme: 5199 sayılı Hayvanları Koruma Kanunu ve ilgili yönetmelikler gereği; Platform üzerinden evcil hayvanların (kedi, köpek vb.) ticari satışı, takası veya para karşılığı devri kesinlikle yasaktır. İlanlar  'Ücretsiz Sahiplendirme' amacıyla da verilemez gizli satış içeren ilanlar derhal yayından kaldırılır ve tekrarı halinde üyelik iptal edilir.
Ev Hizmetleri ve İş Arayan İlanı Kısıtlaması: Platform güvenliğini sağlamak ve istismarı önlemek amacıyla; "Bakıcı", "Temizlikçi", "Hasta Bakıcısı", "Masör/Masöz" veya "Ev Yardımcısı" kategorilerinde 'İş Arıyorum' (hizmet vermek istiyorum) türünde ilan verilmesi yasaktır. Bu kategorilerde sadece 'İşveren' (eleman arıyorum) ilanları yayınlanabilir. Üye, kişisel güvenliği ve KVKK gereği telefon numarasını veya fotoğraflarını "İş Arıyorum" başlığıyla herkese açık paylaşamaz.
Fikri Mülkiyet İhlali ve Uyar-Kaldır Politikası:
1. Replika/Taklit Ürün Yasağı: Üye, Tatildesen.com üzerinde; üçüncü şahısların fikri ve sınai mülkiyet haklarını (Marka, Patent, Tasarım, Telif) ihlal eden; "Replica", "Çakma", "Birebir", "A Kalite", "İhraç Fazlası" veya "Mirror" gibi ifadelerle pazarlanan taklit/sahte ürünleri satamaz. Bu tür ürünlerin satışı Türk Ticaret Kanunu ve Sınai Mülkiyet Kanunu'na göre suçtur.
2. Uyar-Kaldır Prensibi: Tatildesen, 5651 sayılı Kanun kapsamında "Yer Sağlayıcı" sıfatıyla hareket eder. Telif hakkı veya marka sahibi olduğunu belgeleyen kişi/kurumlardan şikayet gelmesi halinde; Tatildesen, ihlale konu ilanı herhangi bir ön incelemeye veya yargı kararına gerek duymaksızın derhal yayından kaldırma, Üye'nin hesabını askıya alma ve Üye'nin kimlik/iletişim bilgilerini yasal süreç başlatılması için hak sahibine veya savcılığa iletme hakkına sahiptir.
3. Tazminat ve Rücu: Üye'nin marka hakkına tecavüz teşkil eden (sahte) ürün satışı nedeniyle, Tatildesen'ın üçüncü kişilere tazminat ödemek zorunda kalması veya idari/adli para cezasına çarptırılması durumunda; ödenen tüm bedeller, avukatlık ücretleri ve dosya masraflarıyla birlikte Üye'ye rücu edilir (yansıtılır).
 
3.3. İlan İçeriği ve Görselleri ile İlgili Kurallar
İlan başlığı ve açıklaması, ilan konusu ile doğrudan ilgili olmalıdır. İlan açıklaması ve görseller, doğrudan satışı yapılan ürün veya hizmetle ilgili olmalıdır. İlan görsellerinde, müstehcen içerikler, yanıltıcı bilgiler, üçüncü kişilere ait hakları ihlal eden içerikler kullanılamaz. Başka bir platformdan alınmış, üzerinde düzenleme yapılmış veya yetkisiz olarak kullanılan görseller içeren ilanlar kaldırılır. Görsellerde web sitesi logosu veya iletişim bilgileri bulunamaz. İlan açıklaması kısmında iletişim bilgileri bulunamaz. Üye, ilan içeriğinde veya fotoğraflarda; başka bir siteye veya sosyal medya profiline yönlendiren link, URL veya QR kod kullanamaz. Platform dışına trafik yönlendirmeyi amaçlayan bu tür ilanlar "Spam/Reklam" sayılarak silinir. EIDS sürecinde, ilan sahibi veya ilanı veren yetkili kişi veya şahıs ile ilan bilgileri arasında uyum olmalıdır. İlan bilgileri ile EIDS sistemi tarafından veya Kültür ve Turizm Bakanlığı tarafından doğrulanan  bilgiler uyuşmadığı takdirde ilanı yayınlamama hakkımız saklıdır. Tatildesen, ilan yayınlama aşamasında e-Devlet entegrasyonu ile EIDS (Elektronik İlan Doğrulama Sistemi) üzerinden kimlik ve yetki doğrulaması yapar. Üye, doğrulama yapmadan ilan veremez. Doğrulama yapılmayan veya manipüle edilen ilanlar nedeniyle kesilecek idari cezalar Üye'ye yansıtılır. Ayrıca Üye, 32 Sayılı Karar gereği ilan fiyatlarını sadece Türk Lirası (TL) cinsinden belirlemek zorundadır. Dövizle ilan girişi yasaktır.Tatildesen.com platformunda yer alan ilanlara ilişkin açıklama metinleri, ilan sahibi kullanıcı tarafından beyan edilen  bilgileri esas alınarak, sistem tarafından otomatik olarak oluşturulmaktadır. Bu otomatik açıklamalar, kullanıcının sağladığı Tip , oda sayısı , havuz ,jakuzi  ve benzeri teknik bilgiler doğrultusunda yapay ilan veren veya zeka destekli sistem aracılığıyla oluşturulmakta olup, bilgilendirme amacı taşır.
İlan açıklamasının doğruluğunun ve yasal uygunluğunun kontrol ve düzenleme sorumluluğu tamamen ilan sahibine aittir. Kullanıcı, platform tarafından oluşturulan açıklamaları kontrol etmekle yükümlü olup, gerektiğinde düzeltme yapabileceğini kabul eder. Tatildesen.com, kullanıcı tarafından sağlanan eksik, yanlış veya yanıltıcı bilgi sebebiyle ortaya çıkabilecek herhangi bir doğrudan ya da dolaylı zarardan sorumlu değildir.
Kullanıcı, beyan ettiği tüm bilgilerin gerçeğe uygun olduğunu ve üçüncü kişi haklarını ihlal etmediğini taahhüt eder. Aksi takdirde doğacak her türlü hukuki ve cezai sorumluluk kendisine aittir.
Görsel İşleme ve Mülkiyet: Üye, yüklediği fotoğrafların Tatildesen sistemleri tarafından (AI, yapay zeka vb.) otomatik olarak iyileştirilmesi durumunda; oluşan yeni ve işlenmiş görselin kullanım hakkının sadece Tatildesen platformuna özgü olduğunu kabul eder. Tatildesen tarafından iyileştirilmiş, filigranlanmış veya işlenmiş görsellerin indirilip başka ilan sitelerinde kullanılması yasaktır.
Cezaların Yansıtılması : Üye'nin hatalı, hileli veya yasa dışı işlemleri yüzünden Tatildesen'ın herhangi bir idari ceza veya tazminat ödemek zorunda kalması durumunda; bu bedel doğrudan Üye'den talep edilir. Üye, kendi kusurundan kaynaklanan bu zararları Tatildesen'a derhal ödemekle yükümlüdür.
Tanıtım ve Kullanım Lisansı: Üye, ilanına eklediği görsellerin ve bilgilerin Tatildesen'ın reklam faaliyetlerinde (Instagram, YouTube, Google Ads vb.) kullanılmasına muvafakat eder. Tatildesen, bu görselleri bedelsiz olarak reklamlarında kullanma hakkına sahiptir. Üye, "İlanım reklamda çıktı, pay istiyorum" gibi bir talepte bulunamaz.
Ayrımcılık ve Oda Arkadaşı Yasağı: Üye, ilanlarında’’ bekara verilmez vb..", gibi ayrımcı, nefret söylemi içeren veya insan haklarına aykırı ifadeler kullanamaz. Ayrıca Tatildesen.com, bir arkadaşlık veya oda paylaşım sitesi değildir; "Ev arkadaşı aranıyor" veya "Sadece oda kiralık" (pansiyon ruhsatı yoksa) şeklindeki ilanlar güvenlik ihlali sayılarak silinir.
3.4. Dolandırıcılığı Önleme ve Güvenlik Politikası
Ödeme işlemleri yalnızca Tatildesen’in sunduğu güvenli ödeme sistemleri (İyzico vb.) aracılığıyla yapılmalıdır.İlansahipleri, kullanıcılar ile güvenli mesajlaşma sistemi üzerinden iletişim kurmalıdır.Tatildesen, sahtekarlık veya dolandırıcılık şüphesi taşıyan ilanları askıya alma, inceleme başlatma ve yasal makamlara bildirme hakkına sahiptir.
İlişkili Hesapların Kapatılması: Üye'nin Platform kurallarını ihlal etmesi nedeniyle hesabı kapatıldığında; Tatildesen güvenlik sistemleri, Üye'nin dijital ayak izlerini (IP, Telefon, Cihaz ID vb.) takip ederek bu Üye'ye ait veya bu Üye ile doğrudan ilişkili olduğu tespit edilen diğer tüm hesapları da (varsa diğer aile üyeleri adına açılmış şüpheli hesaplar dahil) kapatma yetkisine sahiptir. Bu işlem, kötü niyetli kullanımların tekrarını önlemek amacıyla uygulanır ve süresizdir.
Mesaj Güvenliği ve İçerik Taraması: Üye, diğer üyelerle yaptığı yazışmaların; dolandırıcılık, taciz, spam veya Tatildesen dışına yönlendirme girişimlerine karşı otomatik sistemler tarafından taranabileceğini kabul eder. Sistem; IBAN paylaşımı, küfür, hakaret veya şüpheli anahtar kelimeler tespit ettiğinde mesajı sansürleyebilir veya iletilmesini engelleyebilir. Bu işlem, güvenli bir ticaret ortamı sağlamak içindir ve Üye bu güvenlik prosedürüne onay verir.
Sil-Yükle Yasağı: Üye, ilanı öne çıkarmak için "ilanı silip tekrar yükleme" yöntemini kullanamaz. Sistem, aynı ürüne ait ilanın kısa süre içinde tekrar girildiğini (resim hash'i veya metin benzerliği ile) tespit ederse, yeni ilanı reddeder. Bu davranışın süreklilik arz etmesi durumunda hesap "Manipülasyon" gerekçesiyle kapatılır.
3.5. İlan Denetim ve Yayın Süreci
İlanlar, Tatildesen ekibi tarafından manuel ve otomatik (yapay zeka) denetim süreçlerinden geçmektedir.Denetimler sırasında, ilan içeriğinde uygunsuzluk tespit edilirse ilan reddedilir veya düzeltme talep edilir.İlan onay süreci 24 saat içerisinde tamamlanır.İlan sahibi, ilanı düzenleyerek eksiklikleri giderme hakkına sahiptir. Düzenleme yapıldıktan sonra, ilan 24 saat içerisinde tekrar değerlendirmeye alınır.İlan kullanıcı tarafından tekrar düzenlenmesinin ardından firmamızca incelenerek yayına alınır.Her ilan, kategori fark etmeksizin aynı doğrulama sürecine tabidir.
3.6. Görünürlük Kısıtlaması Tatildesen, Platform güvenliğini sağlamak amacıyla; şüpheli davranışlar sergileyen veya spam yapan üyelerin ilanlarını, kullanıcıya haber vermeksizin arama sonuçlarında geri plana atma veya görünmez kılma hakkına sahiptir. Bu bir güvenlik tedbiri olup, Üye bu durumda ilan ücretinin iadesini isteyemez.
 

4. Gizlilik ve Kişisel Verilerin Korunması
4.1. Üyenin kişisel verileri, 6698 sayılı Kişisel Verilerin Korunması Kanunu ve Tatildesen’inGizlilik Politikası’nauygun olarak işlenmekte ve korunmaktadır.
4.2. Üye, ilan ve hesap bilgileri kapsamında Tatildesen tarafından gerçekleştirilen veri işleme süreçlerine ilişkin ayrıntılı bilgilendirmeyi kabul eder.
4.3. Üyenin kişisel verileri yalnızca yasal yükümlülükler çerçevesinde ve hukuki dayanaklar doğrultusunda üçüncü taraflarla paylaşılabilir.
4.4. Daha detaylı bilgi için Açık Rıza Beyanı ve Aydınlatma Metni bağlantılarını inceleyebilirsiniz.
4.5. Üyenin kişisel verileri, 6698 sayılı Kişisel Verilerin Korunması Kanunu ve Tatildesen’inGizlilik Politikası’nauygun olarak işlenmekte ve korunmaktadır.
4.6. Üye, ilan ve hesap bilgileri kapsamında Tatildesen tarafından gerçekleştirilen veri işleme süreçlerine ilişkin ayrıntılı bilgilendirmeyi kabul eder.
4.7. Üyenin kişisel verileri yalnızca yasal yükümlülükler çerçevesinde ve hukuki dayanaklar doğrultusunda üçüncü taraflarla paylaşılabilir.
4.8 SİSTEM GÜVENLİĞİ VE VERİ KORUMA Üye, Tatildesen veritabanındaki ilanları, görselleri veya bilgileri otomatik programlar (bot/crawler) kullanarak toplayamaz. Tatildesen'ın yazılım altyapısını kopyalamaya veya çözmeye (tersine mühendislik) yönelik girişimlerde bulunamaz. Bu tür ihlallerde üyelik iptal edilir ve yasal işlem başlatılır.
4.5 Arama Motoru Sorumluluk Reddi: Üye, sildiği ilanların veya hesabının arama motorlarında (Google vb.) bir süre daha görünebileceğini, bu durumun arama motorlarının kendi indeksleme sisteminden kaynaklandığını bilir. Tatildesen, kendi sunucularından silinen verinin, arama motoru önbelleklerinden de anında silineceğini garanti edemez. Üye, bu tür durumlarda Tatildesen'den tazminat talep etmeyeceğini kabul eder.
 
5. E-Devlet Entegrasyonu
Tatildesen, ilan yayınlama aşamasında e-Devlet entegrasyonu ile kimlik doğrulama işlemleri gerçekleştirebilir.Üyeler, ilanlarını yayınlamadan önce kimlik doğrulama sürecinden geçmeyi kabul eder.İlanlar, Ticaret Bakanlığı sistemlerince denetlenebilir.
6. Ödeme Entegrasyonu 
Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır.Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder.Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
7. BAKIM VE ERİŞİM KISITI  Tatildesen, sisteme ilişkin iyileştirme, güncelleme, bakım veya yenileme çalışmaları nedeniyle Platform'a erişimin geçici olarak durması veya yavaşlaması hallerinden sorumlu değildir. Kullanıcı, bu tür planlı veya zorunlu bakım çalışmaları süresince hizmet verilememesi nedeniyle herhangi bir hak, tazminat veya ilan süresi uzatımı talep edemeyeceğini peşinen kabul eder.
8. MÜCBİR SEBEPLER ve 3. TARAF KAYNAKLI SEBEPLER
Tarafların kontrolü dışında gelişen doğal afetler, savaş, salgın hastalıklar, altyapı sorunları, siber saldırılar, hizmet sağlayıcıların kesintileri, elektrik ve veri merkezi arızaları, telekomünikasyon altyapı problemleri veya yasal düzenlemeler nedeniyle yükümlülüklerin yerine getirilmemesi halinde, taraflar sorumlu tutulamaz.Tatildesen, dışardan gelebilecek herhangi bir siber saldırı, DDOS, veri sızdırma girişimi gibi olaylardan doğabilecek zararlar ve kesintilerden sorumlu tutulamaz. Bu tür mücbir sebep durumlarında, Tatildesen ilgili mercilere bildirimde bulunarak gerekli önlemleri alacak ve sistemleri en kısa sürede yeniden aktif hale getirmek için çalışacaktır.
8.1 HİZMET GARANTİSİ YOKLUĞU (AS IS) Tatildesen, Platform hizmetlerini 'Olduğu Gibi' (As Is) sunmakta olup; hizmetlerin kesintisiz, hatasız, mükemmel olduğu veya Kullanıcı'nın ticari ihtiyaçlarını/beklentilerini tam olarak karşılayacağı taahhüdünde bulunmaz. Yazılım güncellemeleri, teknik arızalar, siber saldırılar, veri merkezi sorunları veya altyapı çalışmaları nedeniyle oluşacak kesintilerden, veri kayıplarından veya ticari zararlardan Tatildesen sorumlu tutulamaz.
9. Uygulanacak Hukuk ve Yetki
Bu Sözleşme, Türkiye Cumhuriyeti yasalarına tabidir. Sözleşmeden kaynaklanabilecek ihtilaflarda Eskişehir Mahkemeleri ve İcra Daireleri yetkilidir.
Delil Sözleşmesi: Üye, işbu Sözleşme’den doğabilecek ihtilaflarda; Tatildesen'in sunucularında tutulan elektronik kayıtların, erişim loglarının ve bilgisayar kayıtlarının HMK Madde 193 uyarınca geçerli ve bağlayıcı delil sayılacağını kabul eder.
BİLDİRİM VE TEBLİGAT ADRESİ Üye'nin sisteme kayıtlı e-posta adresi ve cep telefonu numarası, Tatildesen ile arasındaki tüm iletişimde geçerli yasal tebligat adresi sayılır. Üye, iletişim bilgilerindeki değişiklikleri Tatildesen'e bildirmediği/sistemden güncellemediği takdirde, eski adreslerine yapılan bildirimlerin geçerli olacağını ve kendisine tebliğ edilmiş sayılacağını kabul eder.
Hareketsiz Hesaplar: Tatildesen, son 6 ay (180 gün) boyunca oturum açılmayan veya herhangi bir aktivite (ilan verme, mesajlaşma vb.) göstermeyen ücretsiz üyelikleri, sistem yoğunluğunu azaltmak amacıyla önceden bildirimde bulunmaksızın kapatma ve verilerini silme hakkına sahiptir.
10. Fiyatlandırma ve Ücret Politikası
10.1 Ücretli Hizmetler
Tatildesen.com platformunda sunulan üyelik paketleri, ilan verme hizmetleri ve diğer ücretli servislerin fiyatlandırma politikası, web sitesinde yer alan güncel fiyatlandırma sayfasında belirtilmiştir. Ücretler, hizmetin satın alındığı tarihte geçerli olan tutar üzerinden tahsil edilmektedir. Tatildesen kaynaklı bakım veya teknik kesintiler yayın süresinden sayılır, süreye ekleme yapılmaz. Tek seferlik alınan ilan seçilen paketteki süre ve adet olarak yayında kalır, 1 ayın sonunda kullanıcı ilanı yenilemek isterse yeniden ilan satın almalıdır.Boost paketleri kullanım süresi 1 haftadır ve tek ilan için kullanılabilir, kullanıcı her ilan için ayrı boost paketi satın almalıdır. Bu hizmet, ilana öncelik sağlar ancak sabit bir pozisyon garantisi vermez. Sıralama; algoritma, ilan yoğunluğu ve adil kullanım rotasyonuna göre değişir. Üye, sıralamadaki değişimler nedeniyle iade veya süre uzatımı talep edemez.
Doping/Boost Transfer Yasağı: Satın alınan Doping/Boost hizmeti, sadece uygulandığı ilan için geçerlidir. Dopingli bir ilanın içeriği tamamen değiştirilerek başka bir ürüne dönüştürülemez. Bu hak başka bir ilana devredilemez. İlan yayından kalksa dahi satın alınan sürenin akışı durmaz ve iade edilmez.
Sıralama ve Algoritma Garantisi Yokluğu: Tatildesen, platform üzerindeki arama sonuçlarının sıralamasını, vitrin ilanlarının gösterim sıklığını ve algoritmik yapıyı tek taraflı olarak belirleme ve değiştirme hakkına sahiptir. Ücretli Doping veya ilanım önde gibi hizmeti satın alan Üye, ilanın sadece görünürlüğünün artırıldığını; ancak rakiplerin de benzer hizmeti alması durumunda sistemin "Rastgele" (Random) veya "Sıralı Rotasyon" yöntemini işleteceğini kabul eder. Anlık ekran görüntüleri (Screenshot) alınarak "İlanım en üstte değil" şikayetiyle yapılan iade talepleri, teknik işleyişe aykırı olduğu için reddedilir.
10.2 Ücret  ve  Süre Değişiklikleri
Tatildesen, hizmet bedellerinde ve ilan yayınlama sürelerinde  değişiklik yapma hakkını saklı tutar. Güncellemeler, fiyatlandırma sayfasında yayınlanmak suretiyle kullanıcılara duyurulur ve yayınlandığı andan itibaren geçerlilik kazanır.
10.3 Hizmetlerde İptal İptal işlemi, kullanıcı tarafından talep edildikten sonra 7 iş günü içerisinde işleme alınır ve varsa bakiye borç kullanıcıya bildirilir.
10.4 Fatura ve Ödeme
Tüm ücretli hizmetler, faturalandırma sürecine tabidir ve kullanıcıya elektronik ortamda gönderilir.Ödemeler, platformda belirtilen ödeme yöntemleri (kredi kartı, sanal POS vb.) aracılığıyla yapılır.Ödemelerin düzenli olarak yapılmaması halinde, hizmet askıya alınabilir veya iptal edilebilir.Periyodik abonelik içeren paketlerde, Üye iptal etmediği sürece paket her ay/yıl otomatik yenilenir ve ücret kayıtlı karttan tahsil edilir.
Hizmetlerde İptal ve Ödeme SüreciÖn ödemeli sistemde, kullanıcı bir sonraki dönem için ödeme yapmadan hizmetten yararlanamaz.Eğer kullanıcının taahhüdü yoksa ve ilan yayınlama paket ücreti ödenmezse, ilan yayından kaldırılır.
 
 
İlan Yayından Kaldırılma ve Askıya Alma Süreci
Tatildesen.com olarak, ilanların doğru, eksiksiz ve güncel bilgiler içermesi gerektiğine önem vermekteyiz. Bu nedenle aşağıdaki durumlarda ilanı askıya alma veya yayından kaldırma hakkımız saklıdır:
Arama Motoru Sorumluluk Reddi: Üye, sildiği ilanların veya hesabının arama motorlarında (Google vb.) bir süre daha görünebileceğini, bu durumun arama motorlarının kendi indeksleme sisteminden kaynaklandığını bilir. Tatildesen, kendi sunucularından silinen verinin, arama motoru önbelleklerinden de anında silineceğini garanti edemez. Üye, bu tür durumlarda Tatildesen'den tazminat talep edemeyeceğini kabul eder.
İlanın Gerçeği Yansıtmaması veya Yanıltıcı Bilgi İçermesi:
İlan içeriğinde yanıltıcı, eksik, yanlış veya gerçeği yansıtmayan bilgiler bulunması.İlan görselleri veya videolarının ürün/hizmetle uyumsuz olması veya manipüle edilmiş olması.
Fiyatlandırma Problemleri:
Ürün veya hizmet fiyatının, piyasa değerine göre fahiş şekilde düşük veya yüksek olarak belirlenmesi.İlanın, fiyat spekülasyonu oluşturacak nitelikte düzenlenmesi.
Görsel ve Video Uygunsuzlukları:
İlan görselleri veya videolarında yanıltıcı, manipüle edilmiş veya gerçek dışı içeriklerin yer alması.Üçüncü şahıs haklarını ihlal eden görsellerin kullanılması.
Şikayet ve Bildirimler:
İlan hakkında yapılan şikayetler doğrultusunda yapılan incelemelerde uygunsuzluk veya gerçeği yansıtmama tespit edilmesi.Kullanıcı geri bildirimleri ve üçüncü taraf doğrulamaları ile tespit edilen hatalar.
Tatildesen.com, yukarıda belirtilen durumlarda ilanı askıya alma, yayından kaldırma veya düzenleme talep etme hakkına sahiptir. İlan sahibi, düzeltme yapmadığı sürece ilan tekrar yayına alınmayabilir.
11. SÖZLEŞMENİN BÖLÜNEBİLİRLİĞİ İşbu Sözleşme’nin herhangi bir hükmünün yetkili makamlarca geçersiz sayılması, sözleşmenin geri kalanının geçerliliğini etkilemez. İptal edilen madde dışındaki tüm hükümler, taraflar arasında geçerli ve bağlayıcı olmaya devam eder.
 
12. Yürürlük
Üye, bu Sözleşme ve eklerinde belirtilen tüm şartları elektronik ortamda onaylayarak kabul ettiğini beyan eder. Sözleşme, onay tarihi itibariyle yürürlüğe girer.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme veya paylaşma hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'ın önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'ın onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
TATİLDESEN.COM KİŞİSEL VERİLERİN KORUNMASI VE İŞLENMESİ HAKKINDA AYDINLATMA METNİ
1. Veri Sorumlusu ve Temsilcisi 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) uyarınca, kişisel verileriniz, veri sorumlusu sıfatıyla tatildesen.com (“Şirketimiz”) tarafından aşağıda açıklanan kapsamda işlenebilecektir.
Ticari Ünvan: İbrahim ÖZMEN  Merkez Adresi: KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN  Telefon: 05076123292  E-Posta: tatildesen@gmail.com  
2.İşlenen Kişisel Veriler 
Bireysel kullanıcılarımızdan aşağıdaki kişisel veriler işlenebilmektedir:
Kimlik ve İletişim Bilgileri: Ad, soyad, T.C. kimlik numarası, doğum tarihi, telefon, e-posta,ilgili bakanlıklardan izin belgesi bilgileri 
Fatura ve Vergi Bilgileri: Fatura bilgileri, vergi kimlik numarası, vergi dairesi.Profil Bilgileri: Profil fotoğrafı.
Ticari Elektronik İleti ve İYS Onayı: Üye, Tatildesen.com'a üye olurken veya hizmet alırken paylaştığı iletişim bilgilerine (cep telefonu, e-posta adresi); Tatildesen ve yetkili iş ortakları tarafından kampanya, promosyon, indirim, tanıtım, anket, pazar araştırması ve bilgilendirme amacıyla Ticari Elektronik İleti (SMS, E-posta, MMS, Otomatik Arama vb.) gönderilmesine, verilerinin bu amaçla işlenmesine, saklanmasına ve mevzuat gereği İYS'ye (İleti Yönetim Sistemi)aktarılmasına 6563 sayılı Kanun kapsamında açıkça onay verdiğini kabul ve beyan eder. Üye, dilediği zaman, hiçbir gerekçe göstermeksizin ticari elektronik ileti almayı reddetme (iptal etme) hakkına sahiptir.
 
3. Kişisel Verilerin İşlenme AmaçlarıToplanan kişisel verileriniz, aşağıdaki amaçlarla işlenmektedir:
Kullanıcı hesaplarının oluşturulması ve yönetimi. İlan verme, ilan arama ve görüntüleme hizmetlerinin sunulması.Satıcı ve alıcı arasındaki iletişimin sağlanması. Dolandırıcılık ve sahte ilanların önlenmesi. Güvenli e-ticaret hizmetlerinin yürütülmesi.Kullanıcı deneyiminin iyileştirilmesi.Yasal yükümlülüklerin yerine getirilmesi. Kullanıcılara özel kampanya ve pazarlama faaliyetlerinin yürütülmesi.
Bu işleme faaliyetleri KVKK Madde 5/2(a, c, ç, e, f) ve Madde 6/2 kapsamında işlenmektedir.
4. Kişisel Verilerin Kimlere ve Hangi Amaçla Aktarılabileceği Kişisel verileriniz, KVKK’nın 8. ve 9. maddeleri kapsamında aşağıdaki kişi ve kuruluşlarla paylaşılabilir:
Kişisel verileriniz, yalnızca resmi kurum ve yetkili makamların yazılı talebi ile paylaşılacaktır. Dolandırıcılık ve güvenlik tedbirleri kapsamında iş ortaklarımız. Ödeme hizmeti sağlayıcıları ve bankalar. Sunucu, barındırma ve veri depolama hizmeti veren firmalar. Kullanıcının açık rızası bulunması halinde reklam ve pazarlama faaliyetleri için iş ortaklarımız.
Kredi/Banka kartı bilgisi ödeme aracısı sistem için aktarılır; Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır. Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder. Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
İletişim Güvenliği: Platform içi mesajlaşma içeriklerinin; suç gelirlerinin aklanmasının önlenmesi, dolandırıcılık tespiti ve kullanıcı güvenliğinin sağlanması amacıyla otomatik filtreleme sistemleri ile işlenmesi ve şüpheli durumların ilgili adli makamlara bildirilmesi.
5. Kişisel Verilerin Saklama Süresi
Kişisel verileriniz, ilgili mevzuatta belirtilen süreler boyunca saklanmaktadır:
Hesap bilgileri: Kullanıcı hesabı aktif olduğu sürece saklanır. İşlem kayıtları: 5651 sayılı Kanun gereği 2 yıl boyunca saklanır. Fatura ve finansal kayıtlar: 213 sayılı Vergi Usul Kanunu gereği 5 yıl boyunca saklanır.
Tatildesen.com veritabanından silinen kişisel veriler, üçüncü taraf arama motorlarının (Google vb.) önbelleklerinde bir süre daha erişilebilir olabilir. Bu süreç Tatildesen'in veri sorumluluğu alanının dışındadır.
Üyelik sözleşmesinde belirtilen "Pasif Hesap" kriterlerine uyan ve 6 aydan uzun süre işlem görmeyen hesaplara ait kişisel veriler; yasal saklama zorunluluğu (log kayıtları vb.) bulunanlar hariç olmak üzere, periyodik veri imha süreçlerinde anonimleştirilir veya silinir.
6. Çerezler ve Yurt Dışına Veri AktarımıWeb sitemizde kullanılan çerezler aracılığıyla Google, Meta (Facebook, Instagram), Amazon Web Services (AWS), Microsoft, Apple gibi yurt dışındaki hizmet sağlayıcılarla sınırlı ölçüde veri paylaşımı yapılabilmektedir. Bu paylaşım, reklam, pazarlama, analitik çalışmalar ve kullanıcı deneyiminin iyileştirilmesi amacıyla gerçekleştirilmektedir. Bu kapsamda yalnızca anonimleştirilmiş veriler işlenmekte olup, kimliği doğrudan belirleyici kişisel veriler aktarılmamaktadır. Kullanıcılar, çerez tercihlerini tarayıcı ayarları üzerinden değiştirebilirler.
İlan görselleri ve videoları kişisel veriler hariç olmak üzere yalnızca görseller, yurt dışı sunucularımıza veya hizmet sağlayıcılarına (örneğin, Amazon Web Services vb.) aktarılabilir.
Kişisel veriler yurt dışına aktarılmamaktadır.
7. Meşru Menfaat Kapsamında Kişisel Veri İşleme KVKK’nın 5/2-f maddesi uyarınca, tatildesen.com’un meşru menfaati çerçevesinde aşağıdaki durumlarda kişisel veriler işlenebilir:
Kullanıcı güvenliğini sağlamak ve dolandırıcılığı önlemek.Kullanıcılara yönelik hizmetlerin geliştirilmesi ve özelleştirilmesi. Platformun güvenliğini sağlamak ve teknik sorunları gidermek. Mevcut müşteri ilişkilerinin yönetimi. Kullanıcının yasal haklarının korunması. Kullanıcının onayı olmadan reklam ve pazarlama faaliyetleri yürütülmez. Ancak, mevcut kullanıcılarımızın meşru menfaatler kapsamında hizmetlerinden en iyi şekilde faydalanması için analitik değerlendirmeler yapılabilir.
8. Kişisel Veri Toplama Yöntemi ve Hukuki Sebebi Verileriniz, web sitesi, mobil uygulama, müşteri hizmetleri, çağrı merkezi, çerezler, sosyal medya kanalları ve iş ortaklarımız aracılığıyla KVKK’nın 5. ve 6. maddelerine uygun olarak toplanmaktadır.
9. Veri Sahibi Olarak Haklarınız KVKK’nın 11. maddesi kapsamındaki haklarınız şunlardır:
Kişisel verilerinizin işlenip işlenmediğini öğrenme. İşlenen verilerinizle ilgili bilgi talep etme.Yanlış veya eksik işlenmiş verilerin düzeltilmesini talep etme. Verilerin silinmesini veya yok edilmesini isteme. Kişisel verilerinizin üçüncü kişilere aktarılıp aktarılmadığını öğrenme. Hukuka aykırı veri işleme nedeniyle zarara uğradıysanız tazminat talep etme.
Bu haklarınızı kullanmak için İbrahim ÖZMEN  Merkez Adresi: KAVUNCU MAH.KAVUNCU KÜME EVLER NO:46 GÜNYÜZÜ/ESKİŞEHİR V.K.N.:27952666856 İbrahim ÖZMEN  Telefon: 05076123292  E-Posta: tatildesen@gmail.com adreslerine başvurabilirsiniz ve Noter kanalıyla başvuru yapılabilir.
10. Aydınlatma Metninde Değişiklik Yapılması tatildesen.com, hizmetleri ve mevzuat değişikliklerine bağlı olarak bu metni güncelleme hakkını saklı tutar. Güncellenmiş metin, web sitesi ve mobil uygulama üzerinden yayımlanarak yürürlüğe girecektir.
İLAN VERME KURALLARI
1. Genel Kurallar
İlan veren, mevzuata, Tatildesen.com ilan verme kurallarına ve Üyelik Sözleşmesine uygun hareket etmeyi kabul eder.İlan içeriğinde yanıltıcı, aldatıcı veya gerçeğe aykırı beyanlar bulunamaz.Aynı ürün/hizmet için birden fazla ilan açmak yasaktır. Mükerrer ilanlar yayından kaldırılabilir.İlan başlığı ve açıklaması sadece ilan konusu ile ilgili bilgiler içermelidir. Reklam içerikli ifadeler, linkler veya alakasız bilgiler eklenemez.Ürün veya hizmetin gerçek ve güncel fiyatı belirtilmelidir. Gerçeğe aykırı fiyat yazılamaz.Piyasa değerinden aşırı düşük veya aşırı fazla ilanlar incelemeye alınabilir ve yayından kaldırılabilir. Aynı ürünü, sadece tarihini güncellemek veya öne çıkarmak için silip yeniden yüklemek yasaktır. Bu işlem sistem tarafından engellenir ve ısrarı halinde hesap kısıtlanır. İlanı öne çıkarmak için "Doping" seçenekleri kullanılmalıdır.
2. Yasaklı ve Kısıtlı İçerikler
Telif hakkı, marka hakkı veya fikri mülkiyet haklarını ihlal eden içerikler yasaktır. Her türlü müstehcen, pornografik, nefret söylemi içeren veya terör propagandası yapan ilanlar kaldırılır. Dolandırıcılığa yol açabilecek veya aldatıcı beyan içeren ilanlar yasaktır. Yasalar gereği satışı yasaklanmış ürünler platformda yayınlanamaz. (Örnek: Tütün ürünleri, ilaçlar, sahte belgeler vb.)Yasaklı ve kısıtlı içeriklerin paylaşımından kaynaklanacak her türlü hukuki ve cezai sorumluluk tamamen ilan verene aittir. Bu tür ilanların paylaşımı halinde sorumlu ve muhatap doğrudan ilan veren kullanıcıdır. Tatildesen, yasaklı ürünler listesini güncelleme ve ilanları denetleme hakkına sahiptir.
Evcil Hayvan Satış Yasağı ve Sahiplendirme: 5199 sayılı Hayvanları Koruma Kanunu ve ilgili yönetmelikler gereği; Platform üzerinden evcil hayvanların (kedi, köpek vb.) ticari satışı, takası veya para karşılığı devri kesinlikle yasaktır. Gizli satış içeren ilanlar derhal yayından kaldırılır ve tekrarı halinde üyelik iptal edilir.
Tatildesen.com'da hayvan satışı yasaktır. 
Ev Hizmetleri ve İş Arayan İlanı Kısıtlaması: Platform güvenliğini sağlamak ve istismarı önlemek amacıyla; "Bakıcı", "Temizlikçi", "Hasta Bakıcısı", "Masör/Masöz" veya "Ev Yardımcısı" kategorilerinde 'İş Arıyorum' (hizmet vermek istiyorum) türünde ilan verilmesi yasaktır. Bu kategorilerde sadece 'İşveren' (eleman arıyorum) ilanları yayınlanabilir. Üye, kişisel güvenliği ve KVKK gereği telefon numarasını veya fotoğraflarını "İş Arıyorum" başlığıyla herkese açık paylaşamaz.
Fikri Mülkiyet İhlali ve Uyar-Kaldır Politikası:
1. Replika/Taklit Ürün Yasağı: Üye, Tatildesen.com üzerinde; üçüncü şahısların fikri ve sınai mülkiyet haklarını (Marka, Patent, Tasarım, Telif) ihlal eden; "Replica", "Çakma", "Birebir", "A Kalite", "İhraç Fazlası" veya "Mirror" gibi ifadelerle pazarlanan taklit/sahte ürünleri satamaz. Bu tür ürünlerin satışı Türk Ticaret Kanunu ve Sınai Mülkiyet Kanunu'na göre suçtur.
2. Uyar-Kaldır Prensibi: Tatildesen, 5651 sayılı Kanun kapsamında "Yer Sağlayıcı" sıfatıyla hareket eder. Telif hakkı veya marka sahibi olduğunu belgeleyen kişi/kurumlardan şikayet gelmesi halinde; Tatildesen, ihlale konu ilanı herhangi bir ön incelemeye veya yargı kararına gerek duymaksızın derhal yayından kaldırma, Üye'nin hesabını askıya alma ve Üye'nin kimlik/iletişim bilgilerini yasal süreç başlatılması için hak sahibine veya savcılığa iletme hakkına sahiptir.
3. Tazminat ve Rücu: Üye'nin marka hakkına tecavüz teşkil eden (sahte) ürün satışı nedeniyle, Tatildesen'ınüçüncü kişilere tazminat ödemek zorunda kalması veya idari/adli para cezasına çarptırılması durumunda; ödenen tüm bedeller, avukatlık ücretleri ve dosya masraflarıyla birlikte Üye'ye rücu edilir (yansıtılır).
Yönlendirme ve Spam Yasağı: Üye, diğer kullanıcılara; reklam, tanıtım, zincirleme mesaj, "Kolay para kazanma" teklifleri veya rakip sitelerin linklerini içeren spam mesajlar gönderemez. Tatildesen mesajlaşma sistemi, kullanıcıları site dışına çekmek veya illegal platformlara (bahis, kripto vb.) yönlendirmek için kullanılamaz. Sistem algoritmaları bu tür içerikleri tespit ettiğinde mesajı engeller ve hesabı kapatır.
 
3. İlan İçeriği ve Görsel Kullanımı
İlan görselleri ve videoları, yalnızca ilgili ürün/hizmetle doğrudan bağlantılı olmalıdır. Temsili veya başka kaynaklardan alınan görseller kullanılamaz. İlan görselleri ve videoları ilan konusu taşınmaza veya ürüne ait olmalıdır, başka projelerden veya temsil amaçlı olmamalıdır. Görsellerde firma logoları, telefon numarası, web sitesi adresi veya sosyal medya hesapları yer alamaz. İlan açıklaması, ürün veya hizmetin tüm detaylarını içermeli, yanıltıcı bilgi barındırmamalıdır. Manipüle edilmiş, yanlış bilgi içeren, görsel montaj ile yanıltıcı hale getirilmiş ilanlar yayından kaldırılır.Tatildesen.com platformunda yer alan ilanlara ilişkin açıklama metinleri, ilan sahibi kullanıcı tarafından beyan edile bilgileri esas alınarak, sistem tarafından otomatik olarak oluşturulmaktadır. Bu otomatik açıklamalar, kullanıcının sağladığı tip, metre kare, havuz, jakuzi,  konum, mesafe ve benzeri teknik bilgiler doğrultusunda oluşturulmakta olup, bilgilendirme amacı taşır.
İlan açıklamasının doğruluğunun ve yasal uygunluğunun kontrol ve düzenleme sorumluluğu tamamen ilan sahibine aittir. Kullanıcı, platform tarafından oluşturulan açıklamaları kontrol etmekle yükümlü olup, gerektiğinde düzeltme yapabileceğini kabul eder. Tatildesen.com, kullanıcı tarafından sağlanan eksik, yanlış veya yanıltıcı bilgi sebebiyle ortaya çıkabilecek herhangi bir doğrudan ya da dolaylı zarardan sorumlu değildir.
Kullanıcı, beyan ettiği tüm bilgilerin gerçeğe uygun olduğunu ve üçüncü kişi haklarını ihlal etmediğini taahhüt eder. Aksi takdirde doğacak her türlü hukuki ve cezai sorumluluk kendisine aittir.
Fiyat Geçmişi Gösterimi: Üye, ilan verdiği ürünün fiyatında yaptığı değişikliklerin (indirim veya zam), Tatildesen tarafından kayıt altına alınacağını ve potansiyel alıcılara "Fiyat Geçmişi" grafiği veya listesi olarak gösterilebileceğini kabul eder. Üye, bu özelliğin kapatılmasını talep edemez.
4. Emlak İlanları İçin Özel Kurallar
Tapu ve Ruhsat Bilgileri: Konut  ilanlarında, Turizm konut belgesi’nin bilgileri doğru girilmelidir.
Komisyon ve Yetkilendirme: İlanlar yalnızca işletme ruhsatı sahibi tarıfından verilebilir.Turizm konutu belgesi,Türsab belgesi vs belge sahibi ile banka isim belgesi uyuşmaması durumunda dolandırıcılığa karşı koymak maksatlı ilan verilemez. 
Kiralamalar: Günü birlik konaklama,tekne turları,paraşüt ,dalış,at safari,atv safari vs   ilanlarıda minimum ve maksimum kiralanabilecek gün süresi,konuta giriş çıkış saatleri, diğer aktivitelerde aktivite başlangıç bitiş saatleri belirtilmelidir.
Fiyat Doğruluğu: Kira  bedeli yanlış girilemez. Piyasa değerinden aşırı düşük veya aşırı fazla ilanlar incelenir ve gerekirse yayından kaldırılır.EIDS Süreci: İlan sahibi veya yetkili kişi tarafından girilen ilan bilgilerinin, EIDS sistemi tarafından doğrulanan sahiplik bilgileriyle uyuşması zorunludur. Uyuşmazlık tespit edilirse ilan yayından kaldırılabilir.
Tatildesen, ilan yayınlama aşamasında e-Devlet entegrasyonu ile EIDS (Elektronik İlan Doğrulama Sistemi) üzerinden kimlik ve yetki doğrulaması yapar. Üye, doğrulama yapmadan ilan veremez. Doğrulama yapılmayan veya manipüle edilen ilanlar nedeniyle kesilecek idari cezalar Üye'ye yansıtılır. Ayrıca Üye, 32 Sayılı Karar gereği ilan fiyatlarını sadece Türk Lirası (TL) cinsinden belirlemek zorundadır. Dövizle ilan girişi yasaktır.
Üye, 100 günden kısa süreli (günlük/sezonluk) kiralama ilanlarında; Kültür ve Turizm Bakanlığı'ndan aldığı "Turizm Amaçlı Konut İzin Belgesi" numarasını ilana girmek zorundadır. İzin belgesi olmayan ilanlar sistem tarafından reddedilir veya yayından kaldırılır. Üye, belgesiz kiralama yapması durumunda hem Bakanlık cezalarından hem de Tatildesen'ın uğrayacağı zararlardan (platforma kesilecek cezalar) bizzat sorumludur. Konaklayan misafirlerin kimlik bilgilerinin Emniyet/Jandarma'ya bildirilmesi (KBS/GIYKIMBIL) yükümlülüğü tamamen Üye'ye aittir. Bu yükümlülüklerin ihlali veya belgesiz ilan girişi nedeniyle Tatildesen’a kesilebilecek her türlü idari para cezası, ferileriyle birlikte Üye'ye rücu edilir. Tatildesen, Üye tarafından sisteme girilen 'İzin Belgesi Numarası'nın veya yüklenen belgelerin doğruluğunu, geçerliliğini ve güncelliğini araştırmakla yükümlü değildir. Sistem, Üye'nin beyanını esas alır. Üye'nin sahte, geçersiz, başkasına ait veya iptal edilmiş bir izin belgesi numarası girerek **'Yanıltıcı Beyan'**da bulunması; sistemi ve potansiyel kiracıları kandırması durumunda tüm hukuki ve cezai sorumluluk münhasıran Üye'ye aittir. Bu nedenle Tatildesen'a herhangi bir idari para cezası (Bakanlık cezaları) kesilmesi veya Tatildesen'ın üçüncü kişilere tazminat ödemesi halinde; söz konusu tutarlar ferileriyle birlikte Üye'ye rücu edilir (yansıtılır).

Kiralık Araç Yasağı: Bireysel Üyelik kapsamında "Rent a Car" (Ticari Araç Kiralama) faaliyeti yapılamaz. Kiralık araç ilanları, yalnızca KABİS kaydı bulunan ve yasal izinlere sahip Kurumsal Üyeler tarafından verilebilir. Bireysel hesaptan ticari kiralama ilanı girilmesi yasaktır.
Aktivite İlan Kriterleri:
	•	Deniz Araçları:  Günübirlik,haftalık veya daha uzun süreli tekne turu hizmeti veren üyeler  Deniz Turizmi Araçları İşletme Belgesini sisteme yüklemesi zorunludur. Belge yüklenmemiş ve Kültür ve Turizm Bakanlığı’ndan doğruluğu yapılamayan ilanlar yayınlanmaz veya yayından kaldırılır. Başkalarına ait belgeleri yükleyerek veya belgede sahtecilik ile verilen ilanlardan tatildesen sorumlu değildir. . Belgelerin geçerliliğini sorgulamak üyenin sorumluluğundadır.

	•	. Yamaç Paraşütü:  Beraberinde  Yolcu uçurmak için girilecek ilanlarda pilot’’Ticari Tandem ‘’ T2 Ticari tandem Sertifikasını sisteme yüklemeyi kabul eder. Genel sağlık muayenesi sağlık raporu ,ferdi kaza ve kolluk sigortası vs belgelerin güncel ,geçerli olduğunu (ilan tarihinde geçerli olan ancak ilan süresi içinde geçerliliğini koruduğunu) tatildesen taahüt etmez. Belgelerin geçerliliğini sorgulamak üyenin sorumluluğundadır.
	•	Sportif Amaçlı Su Faaliyeti: Bu alanda verilecek ilanlar için faaliyeti veren işletmenin
  Deniz Turizmi Aracı İşletme Belgesi, Sportif Turizm Yeterlilik Belgesini sisteme yükler.

 Ödeme Güvenliği ve Dolandırıcılığın Önlenmesi
Ödeme işlemleri yalnızca Tatildesen’in sunduğu güvenli ödeme sistemleri (İyzico vb.) üzerinden yapılmalıdır. Harici yollarla yapılan ödemelerden doğacak sorunlardan Tatildesen sorumlu değildir.İlan sahipleri, kullanıcılarla Tatildesen platformu üzerinden iletişim kurmalıdır. Harici iletişim kanalları üzerinden yapılan anlaşmalardan platform sorumlu tutulamaz.Tatildesen, dolandırıcılık veya kötü niyetli kullanım şüphesi olan ilanları inceleme altına alma ve yayından kaldırma hakkına sahiptir.
7. İlan Denetim ve Onay Süreci
İlanlar, Tatildesen ekibi tarafından manuel ve otomatik (yapay zeka) denetim süreçlerinden geçer.Denetim sürecinde ilan içeriği eksik veya hatalı bulunursa ilan reddedilir ya da düzeltme talep edilir.İlanın yayına alınma süresi en fazla ortalama 24 saattir. Ancak gerekli kontrollerin yapılabilmesi için süreç uzayabilir.Tatildesen, kullanıcı deneyimini geliştirmek amacıyla ilanların kategori ve açıklamalarında değişiklik yapma hakkına sahiptir.
8. Yasal ve İdari Düzenlemeler
İlan verenler, yürürlükteki yasalara ve yönetmeliklere uygun hareket etmekle yükümlüdür.Kimlik doğrulama süreçleri eksiksiz tamamlanmalıdır. Kimlik doğrulamayan kullanıcılar ilan veremez.İlanların yasal gereklilikleri karşılamaması halinde Tatildesen, ilgili mercilere bildirimde bulunabilir.İlan içeriklerinde kişisel verilerin korunmasına özen gösterilmelidir. Üçüncü tarafların kişisel verilerinin izinsiz paylaşımı yasaktır.
İLAN YAYINLAMA VE SATIŞ SORUMLULUĞU POLİTİKASI
1. Genel Açıklama Tatildesen Bilişim A.Ş. Tatildesen.com ("Platform"), kullanıcıların ürün ve hizmet ilanlarını yayınlamasına olanak sağlayan bir ilan platformudur. Platformumuz, ilan sahipleri ile alıcıları bir araya getiren bir pazar yeri görevi görür. Tatildesen Bilişim A.Ş. Tatildesen.com, herhangi bir ürün veya hizmetin satışını doğrudan gerçekleştirmez ve ticari işlemlerde taraf değildir.
2. Tatildesen.com’un Sorumlulukları
Tatildesen.com, kullanıcıların ilanlarını yayınlaması için bir altyapı sunar ancak satıcı ile alıcı arasındaki ticari işlemlere müdahil olmaz.Platform, satıcıların beyan ettiği bilgileri doğrulamakla yükümlü değildir ve satıcı ile alıcı arasındaki uyuşmazlıklara doğrudan taraf olmaz.Satıcılar tarafından yayınlanan ilan içeriklerinin doğruluğu, ilan edilen ürün veya hizmetlerin kalitesi ve satış sonrası hizmetlerden yalnızca ilan sahibi (satıcı) sorumludur.İlan sahiplerinin sunduğu bilgiler ile EIDS (E-İlan Doğrulama Sistemi) üzerinden doğrulanan bilgiler arasında uyum olması zorunludur. İlan bilgileri ile EIDS sisteminden gelen bilgiler arasında uyumsuzluk tespit edilirse, ilan yayından kaldırılabilir ve satıcıya bildirim yapılır. İlan verene ait kimlik ve yetki bilgilerinin doğruluğundan yalnızca ilan sahibi sorumludur.
Tatildesen, ilan yayınlama aşamasında e-Devlet entegrasyonu ile EIDS (Elektronik İlan Doğrulama Sistemi) üzerinden kimlik ve yetki doğrulaması yapar. Üye, doğrulama yapmadan ilan veremez. Doğrulama yapılmayan veya manipüle edilen ilanlar nedeniyle kesilecek idari cezalar Üye'ye yansıtılır. Ayrıca Üye, 32 Sayılı Karar gereği ilan fiyatlarını sadece Türk Lirası (TL) cinsinden belirlemek zorundadır. Dövizle ilan girişi yasaktır.
3. Satıcıların Yükümlülükleri
Satıcılar, ilan verdikleri ürün veya hizmetlerin açıklamalarını eksiksiz ve doğru şekilde sunmakla yükümlüdür. Satıcılar, satışa sundukları ürün veya hizmetin hukuka uygun olduğunu ve gerekli izinleri aldığını taahhüt eder, aksi durumda satıcı bizzat sorumludur. Satış sonrası destek, iade ve garanti gibi süreçlerden tamamen satıcı sorumludur. Satıcı, bu süreçleri ilan detaylarında belirtmek zorundadır.
4. Alıcıların Bilgilendirilmesi
Alıcılar, satın almadan önce satıcı ile iletişime geçerek ürün veya hizmet hakkında detaylı bilgi almalıdır. Platform, satıcılar tarafından sağlanan bilgilerin doğruluğunu garanti etmez ve yanlış beyanlar nedeniyle doğabilecek zararlardan sorumlu tutulamaz. Alıcı, herhangi bir uyuşmazlık durumunda satıcı ile iletişime geçerek çözüm aramakla yükümlüdür. Tatildesen.com bu gibi durumlarda satıcı mağaza görseli, telefon ve isim bilgileri alıcı ile paylaşabilir.
5. Hukuki ve İdari Sorumluluklar
Tatildesen.com, kullanıcılar arasında doğabilecek anlaşmazlıklara müdahale etmez ve hukuki süreçlere taraf olmaz. Platformda yayınlanan ilanların içeriklerinden yalnızca ilan sahipleri (satıcılar) sorumludur.Tatildesen.com, herhangi bir kullanıcının yaptığı alışverişten veya ticari faaliyetten doğabilecek zarar veya kayıplardan sorumlu değildir.
Tatildesen, 6563 sayılı Kanun uyarınca yalnızca Aracı Hizmet Sağlayıcı'dır. Tatildesen; Alıcı ve Satıcı arasındaki ürün/hizmet bedeli transferine, kapora ödemesine, ürünün teslimatına, ayıplı mal süreçlerine veya garanti koşullarına taraf değildir, aracılık etmez ve garantör değildir. Kullanıcılar arasındaki para transferi ve ticari anlaşmazlıklar Tatildesen'in sorumluluk alanı dışındadır.
İlan Yayından Kaldırılma ve Askıya Alma Süreci
Tatildesen.com olarak, ilanların doğru, eksiksiz ve güncel bilgiler içermesi gerektiğine önem vermekteyiz. Bu nedenle aşağıdaki durumlarda ilanı askıya alma veya yayından kaldırma hakkımız saklıdır:
İlanın Gerçeği Yansıtmaması veya Yanıltıcı Bilgi İçermesi:
İlan içeriğinde yanıltıcı, eksik, yanlış veya gerçeği yansıtmayan bilgiler bulunması.İlan görselleri veya videolarının ürün/hizmetle uyumsuz olması veya manipüle edilmiş olması.
Fiyatlandırma Problemleri:
Ürün veya hizmet fiyatının, piyasa değerine göre fahiş şekilde düşük veya yüksek olarak belirlenmesi.İlanın, fiyat spekülasyonu oluşturacak nitelikte düzenlenmesi.

Görsel ve Video Uygunsuzlukları:
İlan görselleri veya videolarında yanıltıcı, manipüle edilmiş veya gerçek dışı içeriklerin yer alması.Üçüncü şahıs haklarını ihlal eden görsellerin kullanılması.
Şikayet ve Bildirimler:
İlan hakkında yapılan şikayetler doğrultusunda yapılan incelemelerde uygunsuzluk veya gerçeği yansıtmama tespit edilmesi. Kullanıcı geri bildirimleri ve üçüncü taraf doğrulamaları ile tespit edilen hatalar.
Tatildesen.com, yukarıda belirtilen durumlarda ilanı askıya alma, yayından kaldırma veya düzenleme talep etme hakkına sahiptir. İlan sahibi, düzeltme yapmadığı sürece ilan tekrar yayına alınmayabilir.
Ücretlendirme Politikası
Tüm ücretlendirme ve hizmet bedelleri, Tatildesen.com web sitesinde güncel olarak yayınlanmaktadır. Kullanıcı, hizmet satın almadan önce geçerli fiyatlandırma politikasını incelemekle yükümlüdür. Ücretlendirme ile ilgili değişiklikler, web sitesinde duyurulmak suretiyle yürürlüğe girer ve duyuru yapıldıktan sonraki yeni alımlarda geçerli olur.
 
6. Güncellemeler ve Yürürlük
Tatildesen.com, işbu politikayı dilediği zaman güncelleme hakkını saklı tutar.Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır.İşbu politika, Tatildesen.com internet sitesi ve mobil uygulamaları üzerinden erişilebilir ve kullanıcıların bilgisine sunulmuştur.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızın derhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
 SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'ın önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'ın onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
TOPLULUK KURALLARI & İÇERİK POLİTİKASI
Tatildesen Bilişim A.Ş. Tatildesen.com, kullanıcıların güvenli, adil ve keyifli bir deneyim yaşamasını sağlamak amacıyla aşağıdaki Topluluk Kuralları & İçerik Politikasını oluşturmuştur. Platformu kullanırken bu kurallara uymanız gerekmektedir.
1. KULLANICI DAVRANIŞ KURALLARI
Tatildesen.com kullanıcıları;
Saygılı ve dürüst olmalı, diğer kullanıcılara karşı hakaret, tehdit veya ayrımcılık içeren ifadeler kullanmamalıdır. Dolandırıcılık, sahtekarlık veya yanıltıcı içerikler paylaşmamalıdır. Spam ve gereksiz tekrar eden içerikler eklememelidir. Başkalarının gizlilik haklarına saygı göstermelidir. Kullanıcı bilgilerini izinsiz paylaşmak yasaktır.
Tatildesen markası hakkında sosyal medyada veya diğer platformlarda gerçeğe aykırı karalama kampanyası yürütmek, asılsız "dolandırıcı" iddiasında bulunmak veya marka itibarını hedef alan organize saldırılar düzenlemek yasaktır.
İhlal Durumunda: Kullanıcı hesapları askıya alınabilir, içerikleri kaldırılabilir veya her türlü cezai ve hukuki yasal süreç başlatılabilir.
2. PLATFORMDA YASAKLI İÇERİKLER
Aşağıdaki içerik türleri kesinlikle yasaktır: Müstechen, pornografik, şiddet içerikli veya nefret söylemi içeren içerikler. Irk, din, cinsiyet, siyasi görüş veya engellilik durumuna yönelik ayrımcılık içeren içerikler. Uyuşturucu, alkol veya tütün ürünleriyle ilgili yasa dışı satış teklifleri. Silah, patlayıcı madde veya yasadışı ekipman satışına yönelik içerikler. Yanıltıcı, sahte veya başkalarını dolandırmaya yönelik ilan ve içerikler, terör ve propaganda içerikleri, Telif hakkı ihlali içeren görseller, metinler veya ürünler.
Kullanıcı adı veya mağaza ismi olarak; telefon numarası, web sitesi linki veya başkasına ait marka isimlerinin kullanılması yasaktır.
İhlal Durumunda: İçerikler kaldırılır, kullanıcı hesabı askıya alınabilir ve gerekirse yasal mercilere bildirim yapılır.
Ev Hizmetleri ve İş Arayan İlanı Kısıtlaması: Platform güvenliğini sağlamak ve istismarı önlemek amacıyla; "Bakıcı", "Temizlikçi", "Hasta Bakıcısı", "Masör/Masöz" veya "Ev Yardımcısı" kategorilerinde 'İş Arıyorum' (hizmet vermek istiyorum) türünde ilan verilmesi yasaktır. Bu kategorilerde sadece 'İşveren' (eleman arıyorum) ilanları yayınlanabilir. Üye, kişisel güvenliği ve KVKK gereği telefon numarasını veya fotoğraflarını "İş Arıyorum" başlığıyla herkese açık paylaşamaz.


Fikri Mülkiyet İhlali ve Uyar-Kaldır Politikası:
1. Replika/Taklit Ürün Yasağı: Üye, Tatildesen.com üzerinde; üçüncü şahısların fikri ve sınai mülkiyet haklarını (Marka, Patent, Tasarım, Telif) ihlal eden; "Replica", "Çakma", "Birebir", "A Kalite", "İhraç Fazlası" veya "Mirror" gibi ifadelerle pazarlanan taklit/sahte ürünleri satamaz. Bu tür ürünlerin satışı Türk Ticaret Kanunu ve Sınai Mülkiyet Kanunu'na göre suçtur.
2. Uyar-Kaldır Prensibi: Tatildesen, 5651 sayılı Kanun kapsamında "Yer Sağlayıcı" sıfatıyla hareket eder. Telif hakkı veya marka sahibi olduğunu belgeleyen kişi/kurumlardan şikayet gelmesi halinde; Tatildesen, ihlale konu ilanı herhangi bir ön incelemeye veya yargı kararına gerek duymaksızın derhal yayından kaldırma, Üye'nin hesabını askıya alma ve Üye'nin kimlik/iletişim bilgilerini yasal süreç başlatılması için hak sahibine veya savcılığa iletme hakkına sahiptir.
3. Tazminat ve Rücu: Üye'nin marka hakkına tecavüz teşkil eden (sahte) ürün satışı nedeniyle, Tatildesen'ınüçüncü kişilere tazminat ödemek zorunda kalması veya idari/adli para cezasına çarptırılması durumunda; ödenen tüm bedeller, avukatlık ücretleri ve dosya masraflarıyla birlikte Üye'ye rücu edilir (yansıtılır).
 
3. DOLANDIRICILIK VE GÜVENLİK POLİTİKASI
Tatildesen.com kullanıcıların güvenli bir şekilde alışveriş yapabilmesi için aşağıdaki kuralları uygular:
Yanıltıcı ilanlar, aldatıcı bilgiler ve fiyat manipülasyonları yasaktır. Kullanıcılar, ödeme yapmadan önce ilan detaylarını ve satıcı bilgilerini kontrol etmelidir. Platform dışında yapılan ödemeler veya sahte fatura taleplerine dikkat edilmelidir. Şüpheli bir durum fark edilirse destek ekibine bildirilmelidir.
 
Güvenli Alışveriş İçin Öneriler:
Ödemelerinizi yalnızca platform içerisindeki güvenli sistemler üzerinden yapın. Bilinmeyen hesaplara veya üçüncü şahıslara ödeme yapmayın. Şüpheli ilanları "Şikayet Et" butonunu kullanarak bildirin.
 
4. HUKUKİ VE YASAL UYGUNLUK
Tatildesen.com platformunu kullanan tüm kullanıcılar;
Türk Ceza Kanunu, Tüketicinin Korunması Hakkında Kanun, Elektronik Ticaret Kanunu ve diğer ilgili tüm yasal mevzuata uymakla yükümlüdür.İçeriklerinde yasal olmayan ifadeler veya faaliyetler barındıramaz.Vergi ve yasal yükümlülüklerini yerine getirmelidir.
İhlal Durumunda: Kullanıcı hesapları yasalar çerçevesinde incelenebilir ve resmi mercilere rapor edilebilir.
 
5. TELİF HAKKI VE FİKRİ MÜLKİYET POLİTİKASI
Tatildesen.com'da başkalarına ait içerikleri izinsiz paylaşmak yasaktır.
Başkasına ait görseller, videolar, metinler veya marka logoları izinsiz olarak kullanılamaz.Telif hakkı ihlali içeren ilanlar veya içerikler tespit edildiğinde yayından kaldırılır.Hak sahibi, içerik ihlali nedeniyle Tatildesen.com’abaşvurabilir.
İhlal Durumunda: İçerikler kaldırılabilir ve tekrar eden ihlallerde hesap kapatılabilir.
 
6. HESAP GÜVENLİĞİ VE PAYLAŞIM POLİTİKASI
Kullanıcılar, hesap şifrelerini kimseyle paylaşmamalıdır. Hesap güvenliği için iki faktörlü doğrulama (2FA) kullanılması önerilir. Hesabınızı üçüncü kişilere devretmek veya satmak yasaktır.Tatildesen.com tarafından gönderilen resmi e-postalar dışındaki şüpheli e-postalara yanıt vermeyin.
İhlal Durumunda: Hesap güvenliği ihlal edilen kullanıcıların hesapları geçici olarak askıya alınabilir veya kalıcı olarak kapatılabilir. Kural ihlali yapan kullanıcının sadece mevcut hesabı değil, tespit edilen diğer tüm yan hesapları da kapatılır.
Not: Tatildesen.com, topluluk kurallarını ve içerik politikasını değiştirme hakkını saklı tutar. Kullanıcılar, en güncel politika kurallarına uymakla yükümlüdür.
Hesap Kullanım Sorumluluğu: Üye, hesap bilgilerini veya şifresini üçüncü kişilerle (aile üyesi, arkadaş vb.) paylaşması durumunda; bu kişilerin hesap üzerinden yaptığı tüm işlemlerden bizzat sorumludur. Üye, "Hesabımı başkası kullandı" veya "İlanı ben girmedim" iddiasıyla sorumluluktan kaçamaz. Hesap üzerinden gerçekleşen her türlü yasa dışı işlem veya kural ihlalinde, hesap sahibi (Üye) asli fail olarak kabul edilir.
Hesabın Devredilemezliği: Üyelik hakları kişiye özeldir. Üye, hesabını bir başkasına satamaz, devredemez veya kiralayamaz. Kendi hesabı üzerinden, ticari kazanç sağlamak amacıyla başkalarına ait ürünlerin ilanını giremez (İlan Simsarlığı Yasağı). Bu durumun tespiti halinde hesap süresiz kapatılır.
 
KULLANIM KOŞULLARI
 
1. KULLANIM KOŞULLARI
Tatildesen.com internet sitesini veya mobil uygulamalarını kullanmadan önce lütfen aşağıda belirtilen koşulları dikkatlice okuyunuz. Tatildesen.com internet sitesini ziyaret ederek, mobil uygulamalarını kullanarak ve/veya üye olarak, işbu Kullanım Koşullarını okuduğunuzu, içeriğini anladığınızı ve tüm koşulları kabul ettiğinizi beyan edersiniz. Tatildesen.com, kullanım koşullarını ve sunulan hizmetleri önceden haber vermeksizin değiştirme hakkına sahiptir, ancak kullanıcıların hukuki durumunu etkileyen değişiklilikler uygulama veya mail ile bilgilendirilecektir. Kullanıcılar, güncellenmiş kullanım koşullarına uymayı kabul etmiş sayılır.
2. TANIMLAR
Portal: Tatildesen.com’un internet sitesi ve mobil uygulamaları.Kullanıcı: Portala erişen ve hizmetlerden yararlanan her gerçek veya tüzel kişi.Hesap Sahibi: Portalda hesabı bulunan ve hizmetleri kullanan kişi.İçerik: Portalda yer alan her türlü bilgi, yazı, görsel, video ve ses içeriği.Tatildesen Veritabanı: Kullanıcılar tarafından yüklenen içeriklerin saklandığı ve korunduğu sistem.
3. TATİLDESEN HİZMETLERİ
Tatildesen.com aşağıdaki hizmetleri sunar:
Kullanıcılara ilan yayınlama imkanı.Ürün ve hizmetlerin tanıtımını sağlama.Kullanıcılar arasında güvenli bir platform oluşturma. Farklı kategorilerde ilan listeleme hizmeti sunma.Kullanıcılara alıcı ve satıcı arasında mesajlaşma imkanı sunma.
Tatildesen, hizmetleri değiştirme, geliştirme, ekleme veya kaldırma hakkına sahiptir. Kullanıcılar, bu hizmet değişikliklerini kabul etmiş sayılır.
KATEGORİ YÖNETİMİ VE ALGORİTMA YETKİSİ Tatildesen, tamamen kendi takdirine bağlı olarak; Platform üzerindeki kategori yapısını, sınıflandırmaları ve hizmet başlıklarını dilediği zaman önceden bildirmeksizin değiştirebilir. İlanların sıralanması, görüntülenme sıklığı ve arama sonuçlarındaki yeri, Tatildesen'in mülkiyetinde olan ve ticari sır niteliği taşıyan dinamik algoritmalara dayanır. Üye, organik arama sonuçlarında neden üstte veya altta yer aldığına dair Tatildesen'den herhangi bir teknik açıklama, ifşa veya tazminat talep edemez.
Tatildesen.com üzerinde listelenen temizlikçiler,havuzcular, ustalar, nakliyeciler veya hizmet sağlayıcılar, platformun çalışanı veya temsilcisi değildir. Tatildesen, bu kişilerin mesleki yeterliliğini, güvenilirliğini veya iş kalitesini garanti etmez. Hizmet alımı sırasında oluşabilecek zararlardan, hırsızlık veya hasar durumlarından Tatildesen sorumlu tutulamaz. Kullanıcı, hizmet verenle anlaşmadan önce gerekli araştırmayı bizzat kendisi yapmalıdır.
Otomatik İçerik Filtreleme ve Dolandırıcılık Önleme: Tatildesen; platform üzerinden gerçekleşebilecek "Kapora Dolandırıcılığı", kara para aklama ve yasadışı ticareti engellemek amacıyla, site içi mesajlaşma trafiğini yapay zeka ve otomatik filtreleme sistemleri ile 7/24 tarama hakkına sahiptir. Sistem;
1. Mesaj içeriğinde IBAN numarası, ödeme talep eden ifadeler ("Kapora at", "Hesaba geç"),
2. Genel ahlaka aykırı küfür, hakaret, tehdit veya taciz içeren metinler,
3. Yasadışı ürün/hizmet pazarlaması tespit ettiğinde; mesajı alıcıya iletmeme, sansürleme (maskeleme) veya Üye'nin hesabını geçici/kalıcı olarak askıya alma yetkisine sahiptir. Üye, mesajlaşma gizliliğinin; kamu güvenliği, suçun önlenmesi ve platformun temiz kalması amacıyla bu teknik denetimlere tabi olduğunu peşinen kabul eder. Tatildesen, engellenen bir mesaj nedeniyle doğacak ticari kayıplardan sorumlu tutulamaz.
 
 
 
4. KULLANICI YÜKÜMLÜLÜKLERİ
Kullanıcılar, yalnızca hukuka uygun işlemler yapmakla yükümlüdür. Dolandırıcılık, sahte ilan, yanıltıcı bilgi ve aldatıcı içerikler yasaktır. Kullanıcılar, ilan ve mesajlarında genel ahlaka, kamu düzenine ve ticari etik kurallarına uygun hareket etmelidir. Kullanıcı, portal üzerinde gerçekleştirdiği işlemlerden hukuki ve cezai yönden bizzat sorumludur.
Marka ve İtibar: Kullanıcı, Tatildesen markasını ve logosunu izinsiz kullanamaz. Platform hakkında internet ortamında (sosyal medya vb.) asılsız, karalayıcı veya ticari itibarı zedeleyici paylaşımlarda bulunamaz. Bu tür eylemler "Haksız Rekabet" ve "Kişilik Haklarına Saldırı" sayılacağından, Tatildesen'in hesabı kapatma ve yasal yollara başvurma hakkı saklıdır.
Kullanıcı, hesabına erişim yetkisi verdiği kişilerin veya hesabının güvenliğini sağlamayarak yetkisiz erişime sebep olduğu durumların sonuçlarından doğrudan sorumludur.
Kullanıcı Adı Kısıtlaması: Üye, belirleyeceği "Kullanıcı Adı"nda; telefon numarası, e-posta adresi, web sitesi uzantısı (.com vb.) veya hakaret/küfür içeren ifadeler kullanamaz. Tatildesen, platform dışına iletişim yönlendirmesi yapan veya uygunsuz bulunan kullanıcı adlarını otomatik olarak değiştirme veya hesabı dondurma yetkisine sahiptir.
Proje Teslimat ve Tamamlama Sorumluluğu: Tatildesen, 'Proje Satış Ofisi' mağazalarında tanıtılan projelerin inşaat ruhsatlarını kontrol eder ancak projenin tamamlanacağını, zamanında teslim edileceğini veya müteahhit firmanın mali durumunu garanti etmez. Maketten veya topraktan yapılan satışlarda tüm risk (inşaatın durması, iflas vb.) Alıcı ve Satıcı arasındadır; Tatildesen bu süreçte taraf değildir.
5. İÇERİK YÖNETİMİ VE DENETİMİ
Tatildesen, platformda paylaşılan içeriklerin doğruluğunu garanti etmez. Kullanıcılar, yükledikleri içeriklerin yasalara ve portal kurallarına uygun olduğunu taahhüt eder. Sahte ilanlar, yanlış bilgi içeren veya yanıltıcı içerikler tespit edilirse ilan kaldırılabilir ve kullanıcı hesabı askıya alınabilir. Tatildesen, kullanıcıların sunduğu içeriği düzenleme, inceleme veya kaldırma hakkına sahiptir.
6. FİKRİ MÜLKİYET HAKLARI
Portalda yer alan tüm içerik, veri, yazılım, tasarım ve görseller Tatildesen’e aittir.Kullanıcılar, Tatildesen içeriğini kopyalayamaz, işleyemez, dağıtamaz veya üçüncü kişilerle paylaşamaz. Aksi durumda hukuki ve cezai sorumluluğu kullanıcıya aittir.
İÇERİK LİSANSI: Kullanıcı, Platforma yüklediği her türlü içeriğin (ilan, fotoğraf, video); Tatildesen'ın ticari faaliyetleri, tanıtımı ve reklamları kapsamında, yurtiçi ve yurtdışında, herhangi bir telif ücreti ödenmeksizin süresiz olarak kullanılabileceğini kabul eder. Kullanıcı, sisteme içerik yüklediği anda Tatildesen'a bu konuda geniş kapsamlı bir kullanım lisansı vermiş sayılır.
VERİ KAZIMA VE TERSİNE MÜHENDİSLİK YASAĞI: Kullanıcıların veya ziyaretçilerin; Platform üzerindeki herhangi bir veriyi (ilan, fiyat, görsel, kullanıcı bilgisi vb.); bot, örümcek (spider), crawler, screenscraping yazılımları, veri madenciliği veya benzeri otomatik sistemler kullanarak çekmesi, kopyalaması, işlemesi ve başka bir mecrada yayınlaması kesinlikle yasaktır. Platform'un kaynak kodlarına, arayüzüne veya veritabanına yönelik tersine mühendislik (reverse engineering) yapmak, API açıklarını aramak veya sistemin işleyişini bozacak yük bindirmek suçtur. Tatildesen, bu tür faaliyetlerde bulunan IP adreslerini engelleme ve Cumhuriyet Başsavcılığı'na suç duyurusunda bulunma hakkını saklı tutar.
Veritabanı Mülkiyeti: Platform veritabanı, 5846 sayılı Kanun uyarınca Tatildesen'in koruması altındadır. Üye, veritabanının tamamını veya bir kısmını kopyalayarak rakip bir mecrada kullanamaz. Bu tür eylemler 'VeritabanıYapımcısının Hakları'nın ihlali sayılır ve Üye hakkında savcılığa suç duyurusunda bulunulur.
Tatildesen.com veritabanı üzerindeki tüm mali, manevi ve ticari haklar Tatildesen Bilişim A.Ş.'ye aittir. Veritabanı içeriğinin (ilanlar, fiyatlar, kullanıcı verileri) izinsiz olarak kısmen veya tamamen kopyalanması, başka bir sunucuya aktarılması veya işlenmesi; 5846 sayılı FSEK Ek Madde 4 uyarınca suçtur. Tatildesen, veritabanı yapımcısı olarak kanundan doğan tüm dava ve şikayet haklarını saklı tutar.
Platformun sunduğu araçlarla (AI, filtre vb.) değiştirilen veya üretilen içeriklerin mülkiyeti Tatildesen'e aittir, kaynak gösterilerek dahi başka ticari mecralarda kullanılamaz.
Veri Tabanı Mülkiyeti ve Veri Madenciliği Yasağı: Tatildesen Platformu'nda yer alan; ilan metinleri, fiyat verileri, kullanıcı yorumları, istatistiki bilgiler, raporlar, analiz grafikleri ve veri tabanı yapısı üzerindeki tüm mali haklar, mülkiyet hakları ve "Sui Generis Veri Tabanı Hakkı" münhasıran Tatildesen'e aittir. Kullanıcılar veya üçüncü şahıslar (rakip firmalar, veri toplayıcılar);
1. Tatildesen'in yazılı izni olmaksızın site içeriğini kopyalayamaz, başka bir mecrada yayınlayamaz.
2. Site üzerinde "Screen Scraping" (Ekran Kazıma), "Data Mining" (Veri Madenciliği), bot, örümcek (spider) veya otomatik yazılımlar kullanarak veri çekemez.
3. İlan açıklamalarını ve fiyat bilgilerini toplayıp, Tatildesen ile rekabet edecek başka bir veri tabanı oluşturamaz. Bu yasağın ihlali halinde Tatildesen; 5846 sayılı FSEK ve Türk Ticaret Kanunu hükümleri uyarınca "Haksız Rekabet" davası açma ve maddi/manevi tazminat talep etme hakkını saklı tutar.
Genişletilmiş Veri Kullanım Hakkı: Üye, sisteme girdiği ilan metinlerinin, teknik özelliklerin ve fotoğrafların; Tatildesen tarafından işlenmesine, anonimleştirilerek pazar analizi raporlarına dönüştürülmesine, fiyat endekslerinde kullanılmasına ve Tatildesen'ın iş ortaklarıyla (değerleme firmaları vb.) ticari amaçla paylaşılmasına gayrikabili rücu (geri alınamaz) onay verir. Üye, Tatildesen  veritabanında oluşan bu istatistiki veriler üzerinde (kendi ilanı kaynaklı olsa dahi) herhangi bir telif veya hak iddiasında bulunamaz.
 

7. MÜCBİR SEBEP
Aşağıdaki durumlardan doğan hizmet aksaklıklarında Tatildesen sorumlu tutulamaz:
Doğal afetler (deprem, sel, yangın vb.).Siber saldırılar, altyapı sorunları veya hizmet kesintileri. Üçüncü taraf hizmet sağlayıcı kaynaklı arızalar. yasal düzenlemeler nedeniyle hizmetin kısıtlanması.
8. UYGULANACAK HUKUK VE YETKİ
Kullanım Koşulları, Türkiye Cumhuriyeti yasalarına tabidir. Tatildesen ile kullanıcılar arasındaki ihtilaflarda Eskişehir Mahkemeleri ve İcra Daireleri yetkilidir.
9. YÜRÜRLÜK VE KABUL
Bu Kullanım Koşulları, Tatildesen.com’da yayınlandığı tarihten itibaren geçerli olup kullanıcılar tarafından kabul edilmiş sayılır.
Tatildesen, Kullanım Koşulları'nı önceden haber vermeksizin değiştirme hakkını saklı tutar. Değişiklikler sitede yayınlandığı anda yürürlüğe girer ve siteyi kullanmaya devam eden herkes bu değişiklikleri kabul etmiş sayılır.
Kullanıcılar, Tatildesen platformunu kullanarak tüm koşulları kabul etmiş sayılır.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'in onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
HİZMET BEDELİ İADE POLİTİKASI
1. Tatildesen Bilişim A.Ş. Tatildesen.com ("Platform"), satıcıların ilanlarını yayınlamasına olanak sağlayan bir ilan platformudur. Satıcıların ilanlarını yayınlanabilmesi için belirli hizmet bedelleri ve komisyon ücretleri alınmaktadır. İşbu politika, hizmet bedellerinin ve komisyon iade süreçlerinin yanı sıra abonelik iptalleri ve iade politikalarını da kapsamaktadır.
2. Hizmet Bedeli ve Komisyon Ücretleri
Satıcılar, ilanlarını yayınlamak veya platform içi ek hizmetlerden yararlanmak için belirlenen hizmet bedellerini ödemekle yükümlüdür.
3. Hizmet Bedeli ve Komisyon İade Koşulları
İlan Yayınlama Ücreti: Yayınlanan bir ilan için alınan ücret, ilan yayında olduğu sürece iade edilmez. Hatalı İşlem veya Çift Tahsilat: Teknik bir hata nedeniyle fazla tahsil edilen komisyon veya hizmet bedelleri, inceleme sonrasında satıcıya iade edilir. Özel Kampanya ve İndirimler: Kampanya kapsamında belirlenen hizmet bedelleri ve komisyonlar, iade süreçlerinde kampanya şartlarına göre değerlendirilir.
4. Abonelik İptali ve İade Politikası
Abonelik İptali: Kurumsal ve bireysel üyeler, aboneliklerini diledikleri zaman iptal edebilir. Ancak, taahhütlü aboneliklerde erken iptal yapılması halinde, cayma bedeli tahsil edilir.
İptal ve İade Süreci:
İade ve iptal işlemleri, kullanıcının talebi üzerine platform üzerinden başlatılır. Yıllık ve altı aylık  paketler  turizmin 12 aya yayılması amacıyla uygun fiyatlandırılmaktadır. Sezon başlangıcında uygun paketi alarak sezon bittiğinde üyeliği iptal ederek indirimli olan ücreti geri almak için yapılan başvurulara karşı olarak yıllık ve altı aylık  ilan ücretlerinde iade yapılmayacağını üyeler şimdiden kabul eder. Aylık, üç aylık paketlerde İade koşullarına uygun görülen tutarlar, ilgili ödeme aracısının politikalarına göre belirlenir. İade edilecek tutar, ödeme aracısı (sanal POS firması) tarafına bildirilir ve kullanıcının hesabına aktarılır. İade süresi, ödeme aracısının işlem sürecine bağlı olup, bu süreye platform müdahale edemez. Kart güvenliği ve iade süreci tamamen ödeme aracısının hüküm ve koşullarına tabidir. Muhatap, doğrudan ödeme aracısıdır.
5. İade Koşulları
Üye tarafından satın alınan ilan hakları, doping (boost) hizmetleri ve üyelik paketleri; elektronik ortamda anında ifa edilen gayrimaddi mal niteliğinde olduğundan, yasal mevzuat gereği Cayma Hakkı kapsamında değildir. Üye, satın alma onayını verdiği andan itibaren hizmetin ifa edildiğini ve cayma hakkını kullanarak iade talep edemeyeceğini peşinen kabul eder. 
Kural İhlali ve Ücretin Yanması: Üye'nin ilanı veya hesabı; genel ahlaka aykırılık, dolandırıcılık şüphesi, yanıltıcı fiyat, spam veya Platform kurallarını ihlal etmesi nedeniyle yayından kaldırılırsa veya askıya alınırsa; ödenen hiçbir ücret (ilan, doping, üyelik vb.) iade edilmez. Üye, kurallara uymamanın bir yaptırımı olarak bakiye tutarın Tatildesen uhdesinde kalacağını peşinen kabul eder.

6. Güncellemeler ve Yürürlük
Tatildesen.com, hizmet bedeli, komisyon ve iade politikasını dilediği zaman güncelleme hakkını saklı tutar.Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır.İşbu politika, Tatildesen.com internet sitesi ve mobil uygulamaları üzerinden erişilebilir ve kullanıcıların bilgisine sunulmuştur.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir. (Not: Mevcut ücretli paket sahipleri için fiyat artışı, paketin süresi dolana kadar yansımaz; ancak diğer kullanım kuralları ve sözleşme şartları anında geçerli olur.)
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'ın önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'in onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
 
8.⁠ ⁠Sorumluluk Reddi ve Aracı Hizmet Sağlayıcı Beyanı: Tatildesen, 6563 sayılı Kanun uyarınca yalnızca Aracı Hizmet Sağlayıcı'dır. Tatildesen; Alıcı ve Satıcı arasındaki ürün/hizmet bedeli transferine, kapora ödemesine, ürünün teslimatına, ayıplı mal süreçlerine veya garanti koşullarına taraf değildir, aracılık etmez ve garantör değildir. Kullanıcılar arasındaki para transferi ve ticari anlaşmazlıklar Tatildesen'in sorumluluk alanı dışındadır. 
Tatildesen.com, alıcı ve satıcı arasında gerçekleşen alım-satım sözleşmesinin veya ticari işlemin tarafı değildir.
 
Portalda yayınlanan ilanlardaki ürünlerin kalitesi, orijinalliği (sahteliği), garantisi, ayıplı olup olmaması, ilanın içeriğinin doğruluğu veya ürünün yasalara uygunluğu Tatildesen.com'un taahhüdü ve sorumluluğu altında değildir.
 
Alım-satım, teslimat, ödeme, iptal, iade, garanti ve satış sonrası hizmetlere ilişkin tüm süreçler ve yasal yükümlülükler doğrudan Alıcı ile Satıcı (Üye) arasında yürütülür. Tatildesen.com, bu süreçlere hiçbir şekilde müdahil olmaz ve bu süreçlerden kaynaklanan uyuşmazlıklarda taraf değildir.
 
Alıcı, bir ürünü satın almadan önce ilan detaylarını incelemekle, ürünü ve Satıcı (Üye) hakkındaki güvenilirliği araştırmakla bizzat yükümlüdür. Alıcı ile Satıcı arasındaki güven ilişkisi ve alım-satım kararı tamamen Alıcı'nın kendi inisiyatifi ve sorumluluğundadır.
 
Tatildesen.com, kullanıcılar (alıcı ve satıcı) arasında platform üzerinden veya platform dışında doğabilecek hiçbir hukuki, cezai veya mali anlaşmazlıktan sorumlu tutulamaz.
 
 
 
VERİ SAKLAMA & İMHA POLİTİKASI
1. Tatildesen , Tatildesen.com ("Platform"), kullanıcıların kişisel verilerini Kişisel Verilerin Korunması Kanunu (KVKK), Genel Veri Koruma Tüzüğü (GDPR) ve diğer ilgili mevzuatlara uygun olarak saklamakta ve gerektiğinde imha etmektedir. Bu politika, verilerin ne kadar süreyle saklanacağını, hangi yöntemlerle imha edileceğini ve veri güvenliğinin nasıl sağlanacağını düzenler.
 
2. Veri Saklama Süreleri Kullanıcı verileri, işleme amaçları doğrultusunda belirli süreler boyunca saklanır:
Üyelik Bilgileri: Hesap silindiğinde, yasal yükümlülüklere uygun olarak 5 yıl saklanır ve ardından imha edilebilir. Ödeme ve Finansal Veriler: Vergi mevzuatı gereği, işlem tarihinden itibaren 10 yıl süreyle saklanır. Müşteri Destek Kayıtları: Kullanıcı taleplerini değerlendirmek amacıyla en az 2 yıl süreyle saklanır. Çerezler ve Analitik Veriler: Kullanıcının tercih ettiği çerez politikalarına bağlı olarak 1 yıl süreyle saklanır. Hukuki ve Şikayet Kayıtları: Mevcut hukuki yükümlülükler çerçevesinde 10 yıl boyunca saklanabilir.
 
3. Veri Saklama Yöntemleri Tatildesen.com, verileri güvenli sunucularda ve şifrelenmiş formatlarda saklar. Kullanıcı verilerine yetkisiz erişimi önlemek için aşağıdaki güvenlik önlemleri uygulanmaktadır:
Veri Şifreleme: Kullanıcı verileri şifreleme protokolleri ile korunur.Yetkilendirme Politikaları: Yalnızca yetkili personel, belirlenen güvenlik seviyelerine göre verilere erişebilir.Sistem Yedekleme: Veri kaybını önlemek için günlük, haftalık ve aylık yedekleme prosedürleri uygulanır.Sızma Testleri: Düzenli olarak güvenlik denetimleri ve sızma testleri gerçekleştirilir.
 
4. Veri İmha Yöntemleri Tatildesen.com, yasal saklama süresi dolan veya işleme amacı sona eren kişisel verileri silme, anonim hale getirme veya yok etme yöntemleriyle imha eder.
Fiziksel Yok Etme: Kağıt ortamında saklanan belgeler güvenli şekilde imha edilir.Dijital Veri Silme: Sistemlerden silme komutları ile kalıcı olarak veri kaldırılır.Anonimleştirme: Kişisel verilerin kimliği belirlenemeyecek hale getirilerek, analiz ve raporlama amaçlı kullanılmasına devam edilebilir.
5. Kullanıcı Hakları ve Talepler Kullanıcılar, KVKK ve GDPR kapsamında aşağıdaki haklara sahiptir:
Saklanan kişisel verilerine erişim talep edebilir. Verilerinin düzeltilmesini veya güncellenmesini isteyebilir. Belirli şartlar altında verilerinin silinmesini talep edebilir. İşlenen verilerinin hangi amaçlarla kullanıldığını öğrenebilir.
6. Veri İhlali Bildirimi Tatildesen.com, herhangi bir veri ihlali durumunda, ilgili kullanıcılara ve yetkili kurumlara en geç 72 saat içinde bildirimde bulunacaktır. Veri ihlalleriyle ilgili tüm kayıtlar düzenli olarak tutulmaktadır.
7. Ödeme Entegrasyonu 
Tatildesen, ödeme işlemlerinde ödeme aracısı kullanmaktadır .Üyeler, ödeme işlemlerini gerçekleştirirken ödeme aracısının belirlediği güvenlik önlemlerine uymayı kabul eder. Kart bilgileri doğrudan saklanmaz; ödeme aracısının hüküm ve koşulları geçerli olup, kart saklama güvenliği gibi tüm yükümlülükler ödeme aracısı firmaya aittir. Kullanıcı ile ödeme işlemleri konusunda muhatap, doğrudan ilgili sanal POS firmasıdır.
8. Güncellemeler ve Yürürlük
Tatildesen.com, işbu Veri Saklama & İmha Politikasını güncelleme hakkını saklı tutar. Kullanıcılar, platformu kullanarak bu politikayı kabul etmiş sayılır.
Bu politika, Tatildesen.com'da işlem yapan tüm kullanıcılar için bağlayıcıdır ve platformu kullanmaya devam eden kullanıcılar, belirtilen veri saklama ve imha süreçlerini kabul etmiş sayılırlar.
Tatildesen, tamamen kendi takdirine bağlı ve tek taraflı olarak; işbu Sözleşme’yi, eklerini, platform kurallarını ve ücretlendirme politikalarını, uygun göreceği herhangi bir zamanda Portal’da ilan ederek değiştirebilir. Bu değişiklikler, Portal’da yayınlandığı andan itibaren, Üye'ye herhangi bir ayrıca bildirim (e-posta, SMS, arama vb.) yapılmaksızınderhal yürürlüğe girer. Üye, Portal’ı kullanmaya veya hesabına giriş yapmaya devam etmekle; değişen sözleşme şartlarını ve yeni kuralları okuduğunu, anladığını ve peşinen kabul ettiğini beyan eder. Sözleşme ve eklerindeki güncellemeleri periyodik olarak takip etme sorumluluğu bizzat Üye’ye aittir.
SÖZLEŞMENİN DEVRİ 
1. Tatildesen Tarafından Devir: Tatildesen; işbu Sözleşme'yi, Sözleşme'den doğan hak, yetki, alacak ve yükümlülüklerini; kendi sermaye iştiraklerine, ana şirketine, bağlı ortaklıklarına veya ticari faaliyetlerini/varlıklarını devredeceği üçüncü bir gerçek veya tüzel kişiye (şirket birleşmesi, satın alma, devralma vb. durumlarda), Üye'nin ayrıca iznini veya onayını almaksızın devretme hakkına sahiptir. Üye, olası bir devir durumunda Sözleşme'nin devralan kurumla aynı şartlarda devam edeceğini, muhatabının yeni kurum olacağını peşinen kabul eder.
2. Üye Tarafından Devir: Üye, Tatildesen'in önceden yazılı onayı olmaksızın; işbu Sözleşme'yi, kullanıcı hesabını, mağazasını veya Sözleşme kapsamındaki hak ve yükümlülüklerini üçüncü şahıslara devredemez, kiralayamaz veya satamaz. Tatildesen'in onayı olmadan yapılan devirler geçersizdir ve fesih sebebidir.
 
 
 

`;

export default function IndividualMembershipAndListingAgreementPage() {
  return (
    <article className="mx-auto w-full max-w-[820px] space-y-8 px-4 pb-24 pt-10 md:px-0 md:pt-14">
      <header className="space-y-3 text-center">
        <span className="inline-flex items-center justify-center rounded-full bg-primary/10 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-primary">
          Sözleşme
        </span>
        <h1 className="text-3xl font-semibold tracking-tight text-foreground md:text-4xl">
          Bireysel Üyelik ve İlan Yayınlama Sözleşmesi
        </h1>
      </header>

      <section className="rounded-3xl border border-border bg-white/90 p-6 shadow-sm shadow-black/5">
        <div className="whitespace-pre-wrap break-words text-sm leading-relaxed text-muted-foreground">
          {agreementText}
        </div>
      </section>
    </article>
  );
}
